### PR TITLE
fix(shorebird_cli): validate known checksums as part of cached artifact validation

### LINKED ISSUE #1006: fix: invalid or corrupt bundletool
When creating a release, a couple users have reported an error of the form `Failed to extract version code from app bundle: Error: Invalid or corrupt jarfile /path/to/bundletool.jar`

### LINKED ISSUE #2328: fix: bundletool.jar can get corrupted in cache
run shorebird release android --artifact apk

✓ Fetching apps (0.9s)
✓ Building app bundle with Flutter 3.22.2 (72996fba5d) (32.5s)
✓ Building APK with Flutter 3.22.2 (72996fba5d) (16.8s)
✗ Exception: Failed to extract version code from app bundle: Error: Invalid or corrupt jarfile /Users/linxi/.shorebird/bin/cache/artifacts/bundletool/bundletool.jar

### PR DESCRIPTION
**Pull request by bryanoltman**
## Description

The `CachedArtifact` `isUpToDate` method currently just checks whether the file exists and doesn't perform any integrity check. This renames `isUpToDate` to `isValid` and changes it to verify that the artifact on disk has the expected checksum if we know the artifact's checksum at build time.

Fixes https://github.com/shorebirdtech/shorebird/issues/2328
Fixes https://github.com/shorebirdtech/shorebird/issues/1006
Part of https://github.com/shorebirdtech/shorebird/issues/1771 (not yet fixed because we don't currently compute or store the checksum of the `aot_tools.dill` asset)

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore
- [ ] 🧪 Tests

### CODE REVIEW

File: packages/shorebird_cli/lib/src/cache.dart [hunk 1]
```diff
@@ -153,7 +153,20 @@ abstract class CachedArtifact {
   File get file =>
       File(p.join(cache.getArtifactDirectory(fileName).path, fileName));
 
-  Future<bool> isUpToDate() async => file.existsSync();
+  Future<bool> isUpToDate() async {
```
Comment (eseidel) [inline packages/shorebird_cli/lib/src/cache.dart]: I might rename it "validate" since it really doesn't do an "update" check, but also doesn't matter. 🙃

**Review by eseidel — APPROVED** [review]

**Review by erickzanardo — APPROVED** [review]

File: packages/shorebird_cli/lib/src/cache.dart (hunk 1 above)
Comment (bryanoltman) [reply packages/shorebird_cli/lib/src/cache.dart]: Renamed to `isValid`

**Review by felangel — APPROVED** [review]
