### PR TITLE
fix(shorebird_cli): put ios patch artifact in build directory 

### LINKED ISSUE #622: fix: commands that build ipas leave an `aot.out` file in the project root directory
**Description**

After running `shorebird release ios-preview` or `shorebird patch ios-preview`, there is an `aot.out` file in the project's root directory. We should either clean this up or place it in a hidden directory.

### PR DESCRIPTION
**Pull request by bryanoltman**
## Description

Deletes the patch artifact generated by `shorebird patch ios` after it is uploaded.

Fixes https://github.com/shorebirdtech/shorebird/issues/622

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

File: packages/shorebird_cli/lib/src/commands/patch/patch_ios_command.dart [hunk 1]
```diff
@@ -246,6 +246,14 @@ ${summary.join('\n')}
       },
     );
 
+    final cleanupProgress = logger.progress('Cleaning up');
+    try {
+      await aotFile.delete();
```
Comment (felangel) [inline packages/shorebird_cli/lib/src/commands/patch/patch_ios_command.dart]: What are your thoughts on writing it to a temp directory instead? I feel it would be better than to be modifying the user's workspace especially because partial successes would still lead to having the aotFile around.

Comment (bryanoltman) [reply packages/shorebird_cli/lib/src/commands/patch/patch_ios_command.dart]: This is probably a better idea. Will update.

Comment (bryanoltman) [reply packages/shorebird_cli/lib/src/commands/patch/patch_ios_command.dart]: Done.

**Review by felangel — APPROVED** [review]
