### PR TITLE
fix: show friendly error message when GitHub is down

### LINKED ISSUE #3608: fix: Could have a better error message when github is down.
When github is down, we could show a nicer message:

```
flutter upgrade
ProcessException: Process exited abnormally with exit code 128:
remote: Internal Server Error
fatal: unable to access 'https://github.com/flutter/flutter.git/': The requested URL returned error: 500
  Command: git fetch --tags
```

```
shorebird upgrade
✗ Checking for updates (119.1s)
Checking for updates failed: fatal: unable to access 'https://github.com/shorebirdtech/shorebird.git/': The requested URL returned error: 502


If you aren't sure why this command failed, re-run with the --verbose flag to see more information.

You can also file an issue if you think this is a bug. Please include the following log file in your report:
/Users/eseidel/Library/Application Support/shorebird/logs/1770656796116_shorebird.log
```

### PR DESCRIPTION
**Pull request by eseidel**
## Summary

- Adds `GitHubOutageException` to the central `Git.git()` method that detects HTTP 500/502/503 and "Internal Server Error" patterns in git stderr
- Shows users a friendly message: "GitHub appears to be experiencing an outage. Please check https://www.githubstatus.com and try again later."
- Covers all git commands (upgrade, release, clone, fetch, etc.) since detection is in the shared git executor

Closes #3608

## Test plan

- [x] 5 new tests: HTTP 500, 502, 503, Internal Server Error all throw `GitHubOutageException`; non-outage errors still throw `ProcessException`
- [x] `dart analyze --fatal-warnings` passes
- [x] All existing git tests pass
- [ ] CI green

### CODE REVIEW

**Comment by eseidel** [comment]
I'm not sure this is worth doing?  But came up in triage.

**Comment by bdero** [comment]
Looks like this one needs a rebase.

**Comment by eseidel** [comment]
Fixed, sorry.

File: packages/shorebird_cli/lib/src/executables/git.dart [hunk 1]
```diff
@@ -10,6 +10,45 @@ final gitRef = create(Git.new);
...
+  final String message;
+
+  @override
+  String toString() => message;
+}
+
+/// Pattern that matches HTTP server errors (500, 502, 503) or "Internal Server
+/// Error" in git output.
+final _serverErrorPattern = RegExp(
+  'The requested URL returned error: (500|502|503)|Internal Server Error',
```
Comment (bdero) [inline packages/shorebird_cli/lib/src/executables/git.dart]:
```suggestion
  'The requested URL returned error: (500|502|503|504)|Internal Server Error',
```

File: packages/shorebird_cli/lib/src/executables/git.dart [hunk 2]
```diff
@@ -10,6 +10,45 @@ final gitRef = create(Git.new);
 /// The [Git] instance available in the current zone.
 Git get git => read(gitRef);
 
+/// {@template git_server_unreachable_exception}
+/// Exception thrown when a git command fails due to a server error.
+/// {@endtemplate}
+class GitServerUnreachableException implements Exception {
```
Comment (bdero) [inline packages/shorebird_cli/lib/src/executables/git.dart]: Should probably have this extend ProcessException since we gracefully handle that in caller code, otherwise this will bubble up as an unhandled exception and print a full stack trace.

**Review by bdero — APPROVED** [review]
lgtm
