### PR TITLE
fix: better error handling for release with no platforms provided

### LINKED ISSUE #2261: fix: `shorebird release` prints unhelpful error message when no platform is provided.
**Description**

When running `shorebird release` without any platforms, it fails with a message that doesn't tell much: `Bad state: No element`

**Steps To Reproduce**

1. Go to a shorebird proejct
2. Run `shorebird release` intentionally not passing any platforms
3. See `Bad state: No element` error

**Expected Behavior**

It should show a more useful message like `no messages` informed or similar.

### PR DESCRIPTION
**Pull request by erickzanardo**
## Description

Adds a better error handling for the release command when no platforms were provided.

Fixes #2261 

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore
- [ ] 🧪 Tests

### CODE REVIEW

File: packages/shorebird_cli/test/src/commands/release/release_command_test.dart [hunk 1]
```diff
@@ -521,5 +521,25 @@ $exception''',
...
+      });
+
+      test('fails and log the correct message', () async {
+        final exitCode = await runWithOverrides(command.run);
+
+        expect(exitCode, equals(ExitCode.usage.code));
+
+        verify(
+          () => logger.err(
+            'At least one platform must be specified.',
```
Comment (eseidel) [inline packages/shorebird_cli/test/src/commands/release/release_command_test.dart]: Is this all the user sees?  Will they know what to do with that or how to specify a platform?

File: packages/shorebird_cli/test/src/commands/release/release_command_test.dart [hunk 2]
```diff
@@ -521,5 +521,25 @@ $exception''',
         });
       });
     });
+
+    group('when no platform argument is provided', () {
+      // https://github.com/shorebirdtech/shorebird/issues/2261
```
Comment (bryanoltman) [inline packages/shorebird_cli/test/src/commands/release/release_command_test.dart]: I'm not sure this is necessary

File: packages/shorebird_cli/test/src/commands/release/release_command_test.dart (hunk 1 above)
Comment (erickzanardo) [reply packages/shorebird_cli/test/src/commands/release/release_command_test.dart]: yeah, that is the only error message that I implemented, open to suggestions on a better message :)

**Review by bryanoltman — APPROVED** [review]

File: packages/shorebird_cli/test/src/commands/release/release_command_test.dart (hunk 1 above)
Comment (erickzanardo) [reply packages/shorebird_cli/test/src/commands/release/release_command_test.dart]: @eseidel I think they will known what to do as this is probably a often used command and they just did forgot by mistake to add the platforms.

But we could eventually make this message something like:

```
No platforms were provided, use the --platforms argument to provide one or more platforms
```

Wdyt?

Comment (bryanoltman) [reply packages/shorebird_cli/test/src/commands/release/release_command_test.dart]: I agree with @eseidel here—we should endeavor to tell the user how to fix their problems when we can.

Comment (bryanoltman) [reply packages/shorebird_cli/test/src/commands/release/release_command_test.dart]: > `No platforms were provided, use the --platforms argument to provide one or more platforms`

Let's use this.

Comment (erickzanardo) [reply packages/shorebird_cli/test/src/commands/release/release_command_test.dart]: That is fair! I've changed, can you take another look please?

File: packages/shorebird_cli/lib/src/release_type.dart [hunk 3]
```diff
@@ -49,16 +49,22 @@ enum ReleaseType {
...
+          throw ArgumentError('Invalid platform: $platformCliName');
+        }
+        releaseTypeCliNames = [platformCliName];
       }
-      releaseTypeCliNames = [platformCliName];
+    }
+
+    if (releaseTypeCliNames == null) {
+      return const [];
     }
```
Comment (bryanoltman) [inline packages/shorebird_cli/lib/src/release_type.dart]: I don't think we need this early return. `map` on an empty list will return an empty list

**Review by bryanoltman — APPROVED** [review]

File: packages/shorebird_cli/lib/src/release_type.dart (hunk 3 above)
Comment (erickzanardo) [reply packages/shorebird_cli/lib/src/release_type.dart]: oh, but it is not checking on an empty list, it is checking on nullable map, we need an early return.

Either way, your comment made me think and I changed the early return for an elvis operator and a coalesce to empty list directly on the return and I guess it looks better!
