### PR TITLE
fix(shorebird_cli): use `jdk-dir` override for `JAVA_HOME`

### LINKED ISSUE #2657: fix: `shorebird` finds different `java` from `flutter`
https://discord.com/channels/1030243211995791380/1314340830839832586

From the customer:

`flutter doctor`:

```
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc3)
    • Android SDK at /Users/diegoescudero/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0-rc3
    • Java binary at: /Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment Zulu17.54+21-CA (build 17.0.13+11-LTS)
    • All Android licenses accepted.
```

`shorebird doctor`
```
Android Toolchain
  • Android Studio: /Applications/Android Studio.app/Contents
  • Android SDK: /Users/diegoescudero/Library/Android/sdk
  • ADB: /Users/diegoescudero/Library/Android/sdk/platform-tools/adb
  • JAVA_HOME: /Applications/Android Studio.app/Contents/jbr/Contents/Home
  • JAVA_EXECUTABLE: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
  • JAVA_VERSION: openjdk version "21.0.3" 2024-04-16
                  OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)
                  OpenJDK 64-Bit Server VM (build 21.0.3+-79915917-b509.11, mixed mode)
```

Customer reports that this is their `.zshrc`:
```
export JAVA_HOME=/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home
export PATH="/Users/diegoescudero/.shorebird/bin:$PATH"
```

Looks like Shorebird is finding the wrong JAVA_HOME and `java`?

### PR DESCRIPTION
**Pull request by felangel**
## Description

- fix(shorebird_cli): use `jdk-dir` override for `JAVA_HOME` (closes #2657)

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [X] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore
- [ ] 🧪 Tests

### CODE REVIEW

**Review by eseidel — APPROVED** [review]

File: packages/shorebird_cli/lib/src/shorebird_flutter.dart [hunk 1]
```diff
@@ -121,6 +121,32 @@ class ShorebirdFlutter {
...
+        '${result.stderr}',
+        result.exitCode,
+      );
+    }
+    final output = '${result.stdout}';
+    final config = <String, dynamic>{};
+    final lines = LineSplitter.split(output).toList();
+    for (final line in lines.skip(1)) {
+      final parts = line.split(':');
+      if (parts.length == 2) {
```
Comment (eseidel) [inline packages/shorebird_cli/lib/src/shorebird_flutter.dart:141]: This will fail if the key has a `:` in it.  I doubt it matters, but you probably want to split on first-colon and use the remainer as the value.
