### PR TITLE
fix(shorebird_cli): only run project-specific validators when in a shorebird project directory

### LINKED ISSUE #669: fix: `shorebird doctor` should warn if it is not being run at the root of a project directory

### PR DESCRIPTION
**Pull request by bryanoltman**
## Description

Adds `ValidationScope` enum to validators to allow them to specify whether they perform project-specific validation or system-wide validation and updates `shorebird doctor` to only run project-specific validators when in a project directory.

Fixes https://github.com/shorebirdtech/shorebird/issues/669

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

File: packages/shorebird_cli/lib/src/validators/shorebird_version_validator.dart [hunk 1]
```diff
@@ -11,10 +11,11 @@ class ShorebirdVersionValidator extends Validator {
   final Future<bool> Function({required String workingDirectory})
       isShorebirdVersionCurrent;
 
-  // coverage:ignore-start
   @override
   String get description => 'Shorebird is up-to-date';
-  // coverage:ignore-end
+
+  @override
+  ValidatorScope get scope => ValidatorScope.installation;
```
Comment (felangel) [inline packages/shorebird_cli/lib/src/validators/shorebird_version_validator.dart:18]: can a validator have multiple scopes?

**Review by felangel — APPROVED** [review]
LGTM just wondering whether a validator could be associated with more than one scope. That can be a future thing if we have a use-case though.

File: packages/shorebird_cli/lib/src/validators/shorebird_version_validator.dart (hunk 1 above)
Comment (bryanoltman) [reply packages/shorebird_cli/lib/src/validators/shorebird_version_validator.dart:18]: I don't think so? If a validator is checking both project setup and global installation setup, it should probably be split into two validators.
