### PR TITLE
fix(shorebird_cli): provide exportOptionsPlist to all ipa build commands

### LINKED ISSUE #1663: fix: "Runner.app" requires a provisioning profile with the Near Field Communication Tag Reading and Push Notifications features.
I have an application using Flutter flavors. I successfully generated outputs for all flavors using the command shorebird release ios-alpha --flavor xxxx -t lib/xxxx_main.dart and shared them on the store without any issues. However, when I try to create a patch with shorebird patch ios-alpha --flavor xxxx -t lib/xxxx_main.dart, I encounter an error stating 'Runner.app' requires a provisioning profile with the Near Field Communication Tag Reading and Push Notifications features. In the Apple Store, under the Identifiers section, I have defined NFC and Push Notifications for the app ID. I had created a profile for this definition. How can I resolve this issue?
image

### PR DESCRIPTION
**Pull request by bryanoltman**
## Description

Provide a default export options plist to patch IPA builds in addition to release IPA builds. I believe this should fix https://github.com/shorebirdtech/shorebird/issues/1663

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

File: packages/shorebird_cli/test/src/commands/release/release_ios_command_test.dart [hunk 1]
```diff
@@ -17,6 +17,7 @@ import 'package:shorebird_cli/src/doctor.dart';
 import 'package:shorebird_cli/src/logger.dart';
 import 'package:shorebird_cli/src/os/operating_system_interface.dart';
 import 'package:shorebird_cli/src/platform.dart';
+import 'package:shorebird_cli/src/shorebird_build_mixin.dart';
```
Comment (felangel) [inline packages/shorebird_cli/test/src/commands/release/release_ios_command_test.dart:20]: is this import needed?

**Review by felangel — APPROVED** [review]

File: packages/shorebird_cli/test/src/commands/release/release_ios_command_test.dart (hunk 1 above)
Comment (bryanoltman) [reply packages/shorebird_cli/test/src/commands/release/release_ios_command_test.dart:20]: Yep - ExportMethod was moved to `shorebird_build_mixin`. I can move it to its own file if that makes more sense?
