### PR TITLE
fix(shorebird_cli): provide better error message for missing iOS release

### LINKED ISSUE #1261: Bad error message when patching nonexistent iOS release
**Description**

When running `shorebird patch ios-alpha` for a release without iOS artifacts (i.e., a release that was created with `shorebird release android`), the error message shown is `No artifact found for architecture ipa in release [id]`, which is a bit unclear and potentially misleading.

### PR DESCRIPTION
**Pull request by bryanoltman**
## Description

Changes the error message for a missing iOS release from `No artifact found for architecture ipa in release [id]` to `No iOS release found for [version]`.

Fixes https://github.com/shorebirdtech/shorebird/issues/1261

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

File: packages/shorebird_cli/lib/src/commands/patch/patch_ios_command.dart [hunk 1]
```diff
@@ -136,7 +136,11 @@ class PatchIosCommand extends ShorebirdCommand
       releaseVersion: releaseVersion,
     );
 
-    if (release.platformStatuses[ReleasePlatform.ios] == ReleaseStatus.draft) {
+    if (release.platformStatuses[ReleasePlatform.ios] == null) {
+      logger.err('No iOS release found for $releaseVersion.');
```
Comment (eseidel) [inline packages/shorebird_cli/lib/src/commands/patch/patch_ios_command.dart:140]: I suspect you'll end up abstracting this log.  Every platform is going to want it, just with "iOS" substituted.

**Review by eseidel — APPROVED** [review]

File: packages/shorebird_cli/lib/src/commands/patch/patch_ios_command.dart (hunk 1 above)
Comment (bryanoltman) [reply packages/shorebird_cli/lib/src/commands/patch/patch_ios_command.dart:140]: Yeah, I think we probably will want to consolidate our release and patch commands before too long. Lots of duplicated logic (and test logic) between them.
