### PR TITLE
fix(shorebird_cli): validate release version number conforms to semver

### LINKED ISSUE #368: fix(shorebird_cli): shorebird `release` allows non-semver versions
**Description**

It is possible to enter versions not of the format `x.y.z`.

**Steps To Reproduce**

1. Run `shorebird release`
2. Enter 'asdf asdf' as the build number

**Expected Behavior**

An error message or warning is printed and I am stopped from doing this.

**Actual Behavior**

I'm shown no warning, the release is successful, and due to how shorebird determines "latest version", I need to delete and recreate the app to use semver.

### PR DESCRIPTION
**Pull request by bryanoltman**
## Description

Validate the version number provided to `shorebird app release` is a valid semantic version number as per https://semver.org/.

Fixes https://github.com/shorebirdtech/shorebird/issues/368

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

File: packages/shorebird_cli/test/src/commands/release_command_test.dart [hunk 1]
```diff
@@ -253,8 +253,11 @@ Did you forget to run "shorebird init"?''',
     test('aborts when user opts out', () async {
       when(() => logger.confirm(any())).thenReturn(false);
       when(
-        () => logger.prompt(any(), defaultValue: any(named: 'defaultValue')),
-      ).thenReturn(appDisplayName);
```
Comment (bryanoltman) [inline packages/shorebird_cli/test/src/commands/release_command_test.dart:257]: The only `logger.prompt` call in the release command is for the version number, so I think this may have been vestigial.

File: packages/shorebird_cli/lib/src/commands/release_command.dart [hunk 2]
```diff
@@ -117,11 +118,23 @@ Did you forget to run "shorebird init"?''',
...
+      releaseVersionInput = releaseVersionInput ??
+          logger.prompt(
+            'What is the version of this release?',
+            defaultValue: versionString,
+          );
+      try {
+        releaseVersion = Version.parse(releaseVersionInput);
+      } catch (error) {
+        logger.err(
+          '"$releaseVersionInput" is not a valid version number (see https://semver.org/)',
```
Comment (eseidel) [inline packages/shorebird_cli/lib/src/commands/release_command.dart]: I think if I'm seeing this number, I might ask "why do I care?  Why does it need to be semver?  Why are you, my release system telling me how I can name my releases?" :)

Comment (felangel) [reply packages/shorebird_cli/lib/src/commands/release_command.dart]: Yeah that's a good point as well. We might want to leave this as is and instead improve the experience of managing releases so you can delete/edit releases.

Comment (bryanoltman) [reply packages/shorebird_cli/lib/src/commands/release_command.dart]: Fair! I'll update this to ask the user to confirm a non-semver version number, but allow it if they decide they want to proceed.

**Review by felangel — APPROVED** [review]
