### PR TITLE
fix(shorebird_cli): add retry logic to code push network requests

### LINKED ISSUE #790: "The Semaphore timeout period has expired"
this error happend when build new patch

shorebird patch android

✓ Building patch (3.1s)
✗ ClientException with SocketException: The semaphore timeout period has expired.
 (OS Error: The semaphore timeout period has expired.
, errno = 121), address = api.shorebird.dev, port = 51329, uri=https://api.shorebird.dev/api/v1/apps (21.2s)

### LINKED ISSUE #815: feat: add retry logic to commands that require network
Commands that rely on an internet connection (almost all of them) should have retry logic in case of a blip in connectivity, broken pipe, etc. 

See https://github.com/shorebirdtech/shorebird/actions/runs/5521169649/jobs/10068877894?pr=813 for an example of how this can manifest.

Copying in case github decides to clean that up:

```
Run dart test integration_test

running shorebird --version in .
✅ integration_test/shorebird_cli_integration_test.dart: --version
running `flutter create test_app_8d240c1a_a677_4b07_a2fa_df2d61574b33` in /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/bTSLea/flutter directory
running flutter create test_app_8d240c1a_a677_4b07_a2fa_df2d61574b33 in /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/bTSLea/flutter directory
running shorebird init in /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/bTSLea/flutter directory/test_app_8d240c1a_a677_4b07_a2fa_df2d61574b33
❌ integration_test/shorebird_cli_integration_test.dart: create an app with a release and patch (failed)
  Expected: empty
    Actual: 'Unable to extract product flavors.\n'
              'Exception: Downloading https://services.gradle.org/distributions/gradle-7.5-all.zip\n'
              '\n'
              '\n'
              'Exception in thread "main" java.net.SocketException: Broken pipe\n'
              '\tat java.base/sun.nio.ch.NioSocketImpl.implWrite(NioSocketImpl.java:420)\n'
              '\tat java.base/sun.nio.ch.NioSocketImpl.write(NioSocketImpl.java:440)\n'
              '\tat java.base/sun.nio.ch.NioSocketImpl$2.write(NioSocketImpl.java:826)\n'
              '\tat java.base/java.net.Socket$SocketOutputStream.write(Socket.java:[10](https://github.com/shorebirdtech/shorebird/actions/runs/5521169649/jobs/10068877894#step:9:11)35)\n'
              '\tat java.base/sun.security.ssl.SSLSocketOutputRecord.flush(SSLSocketOutputRecord.java:271)\n'
              '\tat java.base/sun.security.ssl.HandshakeOutStream.flush(HandshakeOutStream.java:89)\n'
              '\tat java.base/sun.security.ssl.Finished$T[12](https://github.com/shorebirdtech/shorebird/actions/runs/5521169649/jobs/10068877894#step:9:13)FinishedProducer.onProduceFinished(Finished.java:402)\n'
              '\tat java.base/sun.security.ssl.Finished$T12FinishedProducer.produce(Finished.java:377)\n'
              '\tat java.base/sun.security.ssl.SSLHandshake.produce(SSLHandshake.java:440)\n'
              '\tat java.base/sun.security.ssl.ServerHelloDone$ServerHelloDoneConsumer.consume(ServerHelloDone.java:182)\n'
              '\tat java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396)\n'
              '\tat java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:480)\n'
              '\tat java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:458)\n'
              '\tat java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:201)\n'
              '\tat java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)\n'
              '\tat java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1510)\n'
              '\tat java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:[14](https://github.com/shorebirdtech/shorebird/actions/runs/5521169649/jobs/10068877894#step:9:15)25)\n'
              '\tat java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455)\n'
              '\tat java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)\n'
              '\tat java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:589)\n'
              '\tat java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:187)\n'
              '\tat java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665)\n'
              '\tat java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:[15](https://github.com/shorebirdtech/shorebird/actions/runs/5521169649/jobs/10068877894#step:9:16)89)\n'
              '\tat java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)\n'
              '\tat org.gradle.wrapper.Download.downloadInternal(Download.java:58)\n'
              '\tat org.gradle.wrapper.Download.download(Download.java:44)\n'
              '\tat org.gradle.wrapper.Install$1.call(Install.java:61)\n'
              '\tat org.gradle.wrapper.Install$1.call(Install.java:48)\n'
              '\tat org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)\n'
              '\tat org.gradle.wrapper.Install.createDist(Install.java:48)\n'
              '\tat org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)\n'
              '\tat org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)\n'
              '\n'
              ''
  
  package:matcher                                            expect
  integration_test/shorebird_cli_integration_test.dart 68:5  main.<fn>
```

### PR DESCRIPTION
**Pull request by bryanoltman**
## Description

Wraps code push network requests in `retry`.

(I think) fixes https://github.com/shorebirdtech/shorebird/issues/790
Fixes https://github.com/shorebirdtech/shorebird/issues/815

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

File: packages/shorebird_code_push_client/lib/src/code_push_client.dart [hunk 1]
```diff
@@ -67,7 +68,10 @@ class _CodePushHttpClient extends http.BaseClient {
 
   @override
   Future<http.StreamedResponse> send(http.BaseRequest request) {
-    return _client.send(request..headers.addAll(CodePushClient.headers));
+    return retry(
+      () => _client.send(request..headers.addAll(CodePushClient.headers)),
+      retryIf: (e) => e is! CodePushException,
```
Comment (felangel) [inline packages/shorebird_code_push_client/lib/src/code_push_client.dart]: We should add tests for this. Also I'm not sure this is exactly what we want.

```suggestion
      retryIf: (e) => e is TimeoutException ||  isHttpIOException(e),
```

```dart
bool isHttpIOException(Object e) {
  return e is HttpException ||
      e is TlsException ||
      e is SocketException ||
      e is WebSocketException;
}
```

Comment (bryanoltman) [reply packages/shorebird_code_push_client/lib/src/code_push_client.dart]: Yep, this is still a draft :)

Comment (felangel) [reply packages/shorebird_code_push_client/lib/src/code_push_client.dart]: Also instead of baking this into the code_push_client we could just pass a `RetryClient` as the `HttpClient` from `shorebird_cli`:

```dart
RetryClient(
  httpClient,
  when: (response) => response.statusCode >= 500,
  whenError: (e, _) => isHttpIOException(e),
);
```

Comment (bryanoltman) [reply packages/shorebird_code_push_client/lib/src/code_push_client.dart]: Sounds good

**Comment by bryanoltman** [comment]
Converting back to draft because I just found that `RetryClient` is a thing that exists already 🤦

**Review by felangel — APPROVED** [review]
