### PR TITLE
fix(shorebird_cli): handle exceptions during validation more gracefully

### LINKED ISSUE #357: fix: bad output from validation failure?
```eseidel@erics-mbp test_app % ../_shorebird/shorebird/bin/shorebird --local-engine-src-path=~/Documents/GitHub/engine/src --local-engine=android_arm64_release run
Unhandled exception:
Instance of 'FlutterValidationException'
#0      ShorebirdFlutterValidator._getFlutterVersion (package:shorebird_cli/src/validators/shorebird_flutter_validator.dart:139:7)
<asynchronous suspension>
#1      ShorebirdFlutterValidator.validate (package:shorebird_cli/src/validators/shorebird_flutter_validator.dart:58:37)
<asynchronous suspension>
#2      Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
<asynchronous suspension>
#3      ShorebirdValidationMixin.logValidationIssues (package:shorebird_cli/src/flutter_validation_mixin.dart:8:31)
<asynchronous suspension>
#4      RunCommand.run (package:shorebird_cli/src/commands/run_command.dart:36:5)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#6      ShorebirdCliCommandRunner.runCommand (package:shorebird_cli/src/command_runner.dart:131:18)
<asynchronous suspension>
#7      ShorebirdCliCommandRunner.run (package:shorebird_cli/src/command_runner.dart:92:14)
<asynchronous suspension>
#8      main (file:///Users/eseidel/Documents/GitHub/_shorebird/shorebird/packages/shorebird_cli/bin/shorebird.dart:6:24)
<asynchronous suspension>
```

I suspect my command line arg is wrong, but it could fail better I think?

### PR DESCRIPTION
**Pull request by bryanoltman**
## Description

The ShorebirdFlutterValidator could previously throw unhandled exceptions if it failed to successfully execute `flutter --version`. This change catches those exceptions and treats them as validation errors.

This change also renames `flutter_validation_mixin.dart` to `shorebird_validation_mixin.dart` to reflect the class contained in the file.

Fixes https://github.com/shorebirdtech/shorebird/issues/357.

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

File: packages/shorebird_cli/test/src/validators/shorebird_flutter_validator_test.dart [hunk 1]
```diff
@@ -15,7 +15,7 @@ class _MockPlatform extends Mock implements Platform {}
 class _MockShorebirdProcess extends Mock implements ShorebirdProcess {}
 
 void main() {
-  group('ShorebirdFlutterValidator', () {
+  group(ShorebirdFlutterValidator, () {
```
Comment (eseidel) [inline packages/shorebird_cli/test/src/validators/shorebird_flutter_validator_test.dart:18]: You can pass a class name to group?  til.

**Review by eseidel — APPROVED** [review]
