### PR TITLE
fix(shorebird_cli): use release target platform instead of host platform when checking for flavor support

### LINKED ISSUE #3315: fix: flaorvs not supported on this platform
App ID: 0a2fce66-ced2-4387-bc3b-81eca58c9118

**Description**

Compilation failing due to flavors not set, but when flavor is passed as argument, shorebird does not run.

**Steps To Reproduce**

1. On a flutter project with flavors, setup shorebird for CI
2. Run the command outlined in the logs
3. See that it fails
4. Run `flutter build appbundle --release --dart-define-from-file .env --flavor production`
5. See that it works

**Expected Behavior**

Compile and push successfully

**Screenshots**

**Additional Context**

Command: shorebird patch android --flavor production -- --dart-define-from-file .env

2025-09-17T19:47:43.559709 [env] SHOREBIRD_TOKEN detected
2025-09-17T19:47:43.561865 [env] SHOREBIRD_TOKEN parsed
2025-09-17T19:47:43.612659 Flavors are not supported on this platform.
2025-09-17T19:47:43.613505 Please re-run this command without the --flavor argument. The app id 0a2fce66-ced2-4387-bc3b-81eca58c9118 will be used.
2025-09-17T19:47:43.614385
If you aren't sure why this command failed, re-run with the --verbose flag to see more information.

You can also file an issue if you think this is a bug. Please include the following log file in your report:
/home/gugahoa/.config/shorebird/logs/1758149263546_shorebird.log

2025-09-17T19:47:43.614519 [Process.run] git symbolic-ref HEAD (in /home/gugahoa/.shorebird/bin/cache)
2025-09-17T19:47:43.616306 Exited with code 0
2025-09-17T19:47:43.616349
stdout:
refs/heads/stable

2025-09-17T19:47:43.616430 [Process.run] git rev-parse --verify HEAD (in /home/gugahoa/.shorebird/bin/cache)
2025-09-17T19:47:43.617567 Exited with code 0
2025-09-17T19:47:43.617625
stdout:
b2140cde6c01df34642cd0bbd83a5227bfee82a6

2025-09-17T19:47:43.617686 [Process.run] git remote prune origin (in /home/gugahoa/.shorebird/bin/cache)
2025-09-17T19:47:43.960373 Exited with code 0
2025-09-17T19:47:43.960586 [Process.run] git fetch --tags (in /home/gugahoa/.shorebird/bin/cache)
2025-09-17T19:47:44.287680 Exited with code 0
2025-09-17T19:47:44.287863 [Process.run] git rev-parse --verify @{upstream} (in /home/gugahoa/.shorebird/bin/cache)
2025-09-17T19:47:44.289409 Exited with code 0
2025-09-17T19:47:44.289455
stdout:
b2140cde6c01df34642cd0bbd83a5227bfee82a6

### PR DESCRIPTION
**Pull request by bryanoltman**
## Description

We care about the target platform; the host platform is irrelevant.

Fixes https://github.com/shorebirdtech/shorebird/issues/3315

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore
- [ ] 🧪 Tests

### CODE REVIEW

File: packages/shorebird_cli/lib/src/release_type.dart [hunk 1]
```diff
@@ -1,95 +1,95 @@
...
-
-    return releaseTypeCliNames?.map(
-          (cliName) => ReleaseType.values.firstWhere(
-            (target) => target.cliName == cliName,
-          ),
-        ) ??
-        const [];
-  }
-}
+import 'package:args/args.dart';
```
Comment (felangel) [inline packages/shorebird_cli/lib/src/release_type.dart]: hmm what changed in this file? Hard to see the diff 👀

Comment (bryanoltman) [reply packages/shorebird_cli/lib/src/release_type.dart]: I think I got Windows'ed. Nothing changed in the file, but I had edited it in a previous revision and saved.

**Review by felangel — APPROVED** [review]
