### PR TITLE
fix(shorebird_cli): log stack trace only when using `--verbose`

### LINKED ISSUE #1915: fix: Remove Traceback from CLI
App ID: N/A

**Description**

DX issue with the CLI. Don't include the entire traceback unless --verbose is passed

```console
standardmoshe@mymac glister-frontend % shorebird pach
Missing subcommand for "shorebird patch".

Usage: shorebird patch <subcommand> [arguments]
-h, --help    Print this usage information.

Available subcommands:
  aar             Publish new patches for a specific Android archive release to Shorebird
  android         Publish new patches for a specific Android release to Shorebird.
  ios             Publish new patches for a specific iOS release to Shorebird.
  ios-framework   Publish new patches for a specific iOS framework release to Shorebird.

Run "shorebird help" to see global options.
#0      Command.usageException (package:args/command_runner.dart:466:7)
#1      CommandRunner.runCommand (package:args/command_runner.dart:169:19)
#2      CompletionCommandRunner.runCommand (package:cli_completion/src/command_runner/completion_command_runner.dart:89:18)
#3      ShorebirdCliCommandRunner.runCommand (package:shorebird_cli/src/command_runner.dart:209:32)
#4      ShorebirdCliCommandRunner.run.<anonymous closure> (package:shorebird_cli/src/command_runner.dart:125:19)
#5      _rootRun (dart:async/zone.dart:1399:13)
#6      _CustomZone.run (dart:async/zone.dart:1301:19)
#7      _runZoned (dart:async/zone.dart:1804:10)
#8      runZoned (dart:async/zone.dart:1747:10)
#9      runScoped (package:scoped/src/scoped.dart:64:10)
#10     ShorebirdCliCommandRunner.run (package:shorebird_cli/src/command_runner.dart:124:20)
#11     main.<anonymous closure> (file:///Users/standardmoshe/.shorebird/packages/shorebird_cli/bin/shorebird.dart:30:47)
#12     _rootRun (dart:async/zone.dart:1399:13)
#13     _CustomZone.run (dart:async/zone.dart:1301:19)
#14     _runZoned (dart:async/zone.dart:1804:10)
#15     runZoned (dart:async/zone.dart:1747:10)
#16     runScoped (package:scoped/src/scoped.dart:64:10)
#17     main (file:///Users/standardmoshe/.shorebird/packages/shorebird_cli/bin/shorebird.dart:29:11)
#18     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:33)
#19     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)


If you aren't sure why this command failed, re-run with the --verbose flag to see more information.
```

**Steps To Reproduce**

1. typo while using CLI

**Expected Behavior**

Don't show entire traceback

**Screenshots**

NA

**Additional Context**

NA

### PR DESCRIPTION
**Pull request by borjandev**
## Description

Ensures that stack trace is only logged in verbose mode.

Resolves https://github.com/shorebirdtech/shorebird/issues/1915

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

File: packages/shorebird_cli/lib/src/command_runner.dart [hunk 1]
```diff
@@ -133,9 +133,11 @@ class ShorebirdCliCommandRunner extends CompletionCommandRunner<int> {
     } on FormatException catch (e, stackTrace) {
       // On format errors, show the commands error message, root usage and
       // exit with an error code
+      logger.err(e.message);
+      if (logger.level == Level.verbose) {
+        logger.info('$stackTrace');
```
Comment (felangel) [inline packages/shorebird_cli/lib/src/command_runner.dart]: I think we could've used `logger.detail('$stackTrace')` instead and that would take care of only being visible in verbose mode.

**Review by felangel — APPROVED** [review]
