### PR TITLE
fix(shorebird_cli): always respect build-name and build-number args

### LINKED ISSUE #2301: `build-number` argument not respected for shorebird release
The ReleaseCommand as a `build-number` option that should be forwarded to `flutter build` but is not. https://github.com/shorebirdtech/shorebird/blob/main/packages/shorebird_cli/lib/src/commands/release/release_command.dart#L51-L60

### PR DESCRIPTION
**Pull request by bryanoltman**
## Description

We were previously only using `build-number` for Flutter module releases. Because this argument is respected for all `flutter build` operations, we should support it for all of them if we support it at all.

Fixes https://github.com/shorebirdtech/shorebird/issues/2301

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore
- [ ] 🧪 Tests

### CODE REVIEW

File: packages/shorebird_cli/lib/src/extensions/iterable.dart [hunk 1]
```diff
@@ -0,0 +1,12 @@
+/// Provides the [containsAnyOf] method to all [Iterable]s.
+extension ContainsAnyOf<T> on Iterable<T> {
+  /// Returns `true` if any of the elements in [elements] are in this iterable.
+  bool containsAnyOf(Iterable<T> elements) {
+    for (final element in elements) {
+      if (contains(element)) {
+        return true;
+      }
+    }
+    return false;
```
Comment (bryanoltman) [inline packages/shorebird_cli/lib/src/extensions/iterable.dart]: I was very surprised to not find something in `package:collection` for this. If you're aware of something similar that I missed, please lmk

Comment (eseidel) [reply packages/shorebird_cli/lib/src/extensions/iterable.dart]: This is just `elements.any((e) => iterable.contains(e))`, right?  It's O(N*M) in worst case.

**Review by erickzanardo — APPROVED** [review]

File: packages/shorebird_cli/lib/src/commands/patch/patcher.dart [hunk 2]
```diff
@@ -139,8 +141,17 @@ https://docs.shorebird.dev/status#link-percentage-ios
...
+    // don't want to override them.
+    if (argResults.options.containsAnyOf([
+      CommonArguments.buildNameArg.name,
+      CommonArguments.buildNumberArg.name,
+    ])) {
+      return [];
+    }
+
+    // If the user provided --build-name or --build-number after the --, we
+    // don't want to override them.
```
Comment (felangel) [inline packages/shorebird_cli/lib/src/commands/patch/patcher.dart:154]: Should we refactor the next few lines to use the CommonArguments name instead of a string literal?

File: packages/shorebird_cli/lib/src/extensions/iterable.dart [hunk 3]
```diff
@@ -0,0 +1,5 @@
+/// Provides the [containsAnyOf] method to all [Iterable]s.
+extension ContainsAnyOf<T> on Iterable<T> {
+  /// Returns `true` if any of the elements in [elements] are in this iterable.
+  bool containsAnyOf(Iterable<T> elements) => elements.any(contains);
```
Comment (felangel) [inline packages/shorebird_cli/lib/src/extensions/iterable.dart:4]: What’s the benefit of this extension? Seems like it’s a one liner either way

**Review by felangel — APPROVED** [review]

File: packages/shorebird_cli/lib/src/commands/patch/patcher.dart (hunk 2 above)
Comment (bryanoltman) [reply packages/shorebird_cli/lib/src/commands/patch/patcher.dart:154]: Good call, done

File: packages/shorebird_cli/lib/src/extensions/iterable.dart (hunk 3 above)
Comment (bryanoltman) [reply packages/shorebird_cli/lib/src/extensions/iterable.dart:4]: It looks a bit nicer with list literals:

```dart
argResults.options.containsAnyOf([a,b]);
```

instead of 

```dart
[a,b].any((e) => argResults.options.contains(e));
```

Mostly just a minor readability improvement, happy to remove if you feel strongly.
