### PR TITLE
fix: shorebird preview to identify shorebird projects with flavors

### LINKED ISSUE #1836: fix: `shorebird preview` doesn't think I'm inside a project
Running here:
https://github.com/shorebirdtech/samples/tree/main/flavors

```
PS C:\Users\micro\Documents\GitHub\samples\flavors> ..\..\shorebird\bin\shorebird preview
✓ Fetching apps (0.3s)
Which app would you like to preview?
❯ ◉  test_shorebird
  ◯  fresh_example
  ◯  fresh_dio
  ◯  openreads
  ◯  flutter_amazon_clone_bloc
  ◯  buck_the_critics
  ◯  test_3_16_4
  ◯  test_ios_mix
  ◯  flutter_and_friends
  ◯  fluttersaurus
  ◯  test_3_16_3
  ◯  flavors (stable)
  ◯  flavors (internal)
  ◯  flavors (stable)
  ◯  flavors (internal)
  ◯  test_3_13_9
  ◯  test_3_13_9
  ◯  mixed_test
  ◯  lima_test
  ◯  test_3_13_8
  ◯  flavors (stable)
  ◯  flavors (internal)
  ◯  test_3_13_4
  ◯  test_0_14_8
  ◯  test_0_14_7
  ◯  test_no_android
  ◯  shorebird_code_push_example
  ◯  test_3_13_1
  ◯  my_project
  ◯  test_counter
  ◯  time_shift
  ◯  shorebird_code_push
  ◯  fluttercon_demo
  ◯  ios_test
  ◯  test_app
  ◯  shorebird_hello
  ◯  hello_shorebird
  ◯  win_test
```

### PR DESCRIPTION
**Pull request by erickzanardo**
## Description

Uses the flavor values at `shorebird.yaml` to prompt for which flavor to use when using `shorebird preview`

Fixes #1836 

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

File: packages/shorebird_cli/lib/src/commands/preview_command.dart [hunk 1]
```diff
@@ -76,6 +76,7 @@ class PreviewCommand extends ShorebirdCommand {
 
   @override
   Future<int> run() async {
+    print('Helloo');
     // TODO(bryanoltman): check preview target and run either
```
Comment (bryanoltman) [inline packages/shorebird_cli/lib/src/commands/preview_command.dart]:
```suggestion
  Future<int> run() async {
    // TODO(bryanoltman): check preview target and run either
```

File: packages/shorebird_cli/lib/src/commands/preview_command.dart [hunk 2]
```diff
@@ -88,10 +89,17 @@ class PreviewCommand extends ShorebirdCommand {
...
+
     if (results.wasParsed('app-id')) {
       appId = results['app-id'] as String;
-    } else if (shorebirdYaml != null && shorebirdYaml.flavors == null) {
+    } else if (shorebirdYaml != null && flavors == null) {
       appId = shorebirdYaml.appId;
+    } else if (shorebirdYaml != null && flavors != null) {
+      final flavorOptions = flavors.keys.toList();
+      final choosenOne = await promptForFlavor(flavorOptions);
+      appId = flavors[choosenOne];
```
Comment (bryanoltman) [inline packages/shorebird_cli/lib/src/commands/preview_command.dart]:
```suggestion
      final choosenFlavor = await promptForFlavor(flavorOptions);
      appId = flavors[choosenFlavor];
```

File: packages/shorebird_cli/lib/src/commands/preview_command.dart [hunk 3]
```diff
@@ -172,6 +180,15 @@ class PreviewCommand extends ShorebirdCommand {
...
   }
 
+  Future<String?> promptForFlavor(
+    List<String> flavors,
+  ) async {
+    return logger.chooseOne<String>(
+      'Which app flavor?',
+      choices: flavors,
+    );
+  }
```
Comment (bryanoltman) [inline packages/shorebird_cli/lib/src/commands/preview_command.dart]: I'm not sure we gain much by wrapping this in its own function, as the call to `logger.chooseOne` is not substantially more complex than the call to `promptForFlavor`.

File: packages/shorebird_cli/pubspec.lock
Comment (bryanoltman) [inline packages/shorebird_cli/pubspec.lock:1]: This looks fine, but these updates should usually be in their own commits so we don't roll back more than we need to if something goes wrong.

File: packages/shorebird_cli/test/src/commands/preview_command_test.dart [hunk 4]
```diff
@@ -723,20 +723,18 @@ channel: ${track.channel}
...
+        ).thenReturn('dev');
 
         await runWithOverrides(command.run);
 
         verify(
-          () => logger.chooseOne<AppMetadata>(
-            'Which app would you like to preview?',
+          () => logger.chooseOne<String>(
+            any(),
             choices: any(named: 'choices'),
```
Comment (bryanoltman) [inline packages/shorebird_cli/test/src/commands/preview_command_test.dart]: We should probably verify that the flavors were provided as arguments to `chooseOne`

**Review by bryanoltman — APPROVED** [review]
A couple small comments, but otherwise looks good! I'd suggest adding a note in the PR description explaining how you fixed the issue (something like "detects flavors in shorebird.yaml and prompts user to pick channel instead of app").

File: packages/shorebird_cli/pubspec.lock
Comment (erickzanardo) [reply packages/shorebird_cli/pubspec.lock:1]: You are correct! I am going to revert it!

File: packages/shorebird_cli/test/src/commands/preview_command_test.dart (hunk 4 above)
Comment (erickzanardo) [reply packages/shorebird_cli/test/src/commands/preview_command_test.dart]: Fair enought! I've changed it

**Review by felangel — APPROVED** [review]

File: packages/shorebird_cli/test/src/commands/preview_command_test.dart (hunk 4 above)
Comment (bryanoltman) [reply packages/shorebird_cli/test/src/commands/preview_command_test.dart]: Did you push? I'm still seeing:

```dart
 verify(
          () => logger.chooseOne<String>(
            any(),
```

Comment (erickzanardo) [reply packages/shorebird_cli/test/src/commands/preview_command_test.dart]: Screenshot 2024-04-03 at 13 52 16

I pushed yes! That is weird, I am seeing it correctly as shown in the print above

Comment (bryanoltman) [reply packages/shorebird_cli/test/src/commands/preview_command_test.dart]: Ah! The issue is just that the test only has a single flavor. We should probably update that (and maybe change the command to not prompt if only one flavor is present, although that seems like sort of a silly setup)

Comment (erickzanardo) [reply packages/shorebird_cli/test/src/commands/preview_command_test.dart]: Oh, yeah, fair point!

Should we do that handling in a different PR though? I feel that this PR is addressing the detecting a shorebird project that has flavors, no matter the number, then auto selecting the only flavor would probably be a change of its own?

Let me know if you agree, otherwise I am happy to update this PR to include this as well.

Comment (bryanoltman) [reply packages/shorebird_cli/test/src/commands/preview_command_test.dart]: I think the "single flavor" fix can be done in a future PR (if ever), but the test should probably be updated to include more than one flavor

Comment (erickzanardo) [reply packages/shorebird_cli/test/src/commands/preview_command_test.dart]: Fair enough, I've updated it

**Review by bryanoltman — APPROVED** [review]

**Comment by bryanoltman** [comment]
Looks great, ship it!
