### PR TITLE
fix: accurate message when patching a release that doesn't contains the platform

### LINKED ISSUE #2177: Attempting to run `shorebird patch [platform]` for a release that doesn't have [platform] prints confusing error message
**Description**

When a release exists for one platform (say, Android) but not for another (say, iOS) and one runs `shorebird patch ios --release-version 1.2.3`, the CLI prints:

```
Release 1.0.1+19 is in an incomplete state. It's possible that the original release was terminated or failed to complete.
Please re-run the release command for this version or create a new release.
```

Which is not correct. The release is not in an incomplete state, it just does not exist for the given platform. I think this is a pretty minor issue as the instructions are correct, but we should print a more correct error message.

**Steps To Reproduce**

1. Create an android release with `shorebird release android`
2. Attempt to create an iOS patch with `shorebird patch ios`
3. See the error message

**Expected Behavior**

The CLI prints something like:

```
No release exists for [platform]. Please run shorebird release [platform] to create one.
```

### PR DESCRIPTION
**Pull request by erickzanardo**
## Description

From #2177 

> When a release exists for one platform (say, Android) but not for another (say, iOS) and one runs `shorebird patch ios --release-version 1.2.3`, the CLI prints:
> 
> ```
> Release 1.0.1+19 is in an incomplete state. It's possible that the original release was terminated or failed to complete.
> Please re-run the release command for this version or create a new release.
> ```
> 
> Which is not correct. The release is not in an incomplete state, it just does not exist for the given platform.

This PR adds an additional assertion to check if the release simply doesn't have a platform a logs a better message.

Screenshot 2024-06-19 at 10 08 17

Fix #2177 

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore
- [ ] 🧪 Tests

### CODE REVIEW

File: packages/shorebird_cli/lib/src/commands/patch/patch_command.dart [hunk 1]
```diff
@@ -323,6 +324,20 @@ NOTE: this is ${styleBold.wrap('not')} recommended. Asset changes cannot be incl
...
 
+  void assertReleaseContainsPlatform({
+    required Release release,
+    required Patcher patcher,
+  }) {
+    final containsPlatform = release.platformStatuses
+        .containsKey(patcher.releaseType.releasePlatform);
+    if (!containsPlatform) {
+      logger.err(
+        '''No release exists for [platform]. Please run shorebird release [platform] to create one.''',
```
Comment (bryanoltman) [inline packages/shorebird_cli/lib/src/commands/patch/patch_command.dart]: Why not print the platform instead of `[platform]`?

**Review by bryanoltman — COMMENTED** [review]
LGTM, but we should print a more friendly error message

File: packages/shorebird_cli/lib/src/commands/patch/patch_command.dart (hunk 1 above)
Comment (erickzanardo) [reply packages/shorebird_cli/lib/src/commands/patch/patch_command.dart]: Sounds good! I took this message from the issue. And I just realized the [platform] should be interpolated. Let me add a better one

Comment (erickzanardo) [reply packages/shorebird_cli/lib/src/commands/patch/patch_command.dart]: Changed for `No release exists for android in 1.1.0. Please run shorebird release --platform android to create one.`

Let me know what you think

File: packages/shorebird_cli/lib/src/commands/patch/patch_command.dart [hunk 2]
```diff
@@ -323,6 +324,21 @@ NOTE: this is ${styleBold.wrap('not')} recommended. Asset changes cannot be incl
...
+  void assertReleaseContainsPlatform({
+    required Release release,
+    required Patcher patcher,
+  }) {
+    final releasePlatform = patcher.releaseType.releasePlatform;
+    final contains = release.platformStatuses.containsKey(releasePlatform);
+    if (!contains) {
+      final platformName = releasePlatform.name;
+      logger.err(
+        '''No release exists for $platformName in ${release.version}. Please run shorebird release --platform $platformName to create one.''',
```
Comment (bryanoltman) [inline packages/shorebird_cli/lib/src/commands/patch/patch_command.dart]:
```suggestion
        '''No release exists for $platformName in release version ${release.version}. Please run shorebird release $platformName to create one.''',
```

**Review by bryanoltman — APPROVED** [review]
Minor suggestion for the copy, but lgtm!
