### PR TITLE
fix: gracefully handling patching on a app with no releases

### LINKED ISSUE #2242: `shorebird patch` fails awkwardly if there are no releases
**Description**

We should detect that there are no releases before asking which release they would like to patch.

**Steps To Reproduce**

1. Create a new shorebird app
2. Run `shorebird patch ios`
3. See the following

```
⑆ shorebird patch ios
✓ Fetching apps (0.2s)
✓ Fetching releases (0.1s)
Which release would you like to patch?
Which release would you like to patch? RangeError (index): Invalid value: Valid value range is empty: 0

If you aren't sure why this command failed, re-run with the --verbose flag to see more information.

You can also file an issue if you think this is a bug. Please include the following log file in your report:
/Users/bryanoltman/Library/Application Support/shorebird/logs/1718375682768_shorebird.log
```

### PR DESCRIPTION
**Pull request by erickzanardo**
## Description

`shorebird patch` would fail with a weird message if executed in an app with no releases.

This PR tries to gracefully handle that by displaying a warning and exiting the command.

Fixes #2242

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore
- [ ] 🧪 Tests

### CODE REVIEW

File: packages/shorebird_cli/lib/src/commands/patch/patch_command.dart [hunk 1]
```diff
@@ -308,6 +308,14 @@ NOTE: this is ${styleBold.wrap('not')} recommended. Asset changes cannot be incl
     final releases = await codePushClientWrapper.getReleases(
       appId: appId,
     );
+
+    if (releases.isEmpty) {
+      logger.warn(
+        '''No releases found for app $appId. You need to make first a release before you can create a patch.''',
+      );
+      throw ProcessExit(ExitCode.success.code);
```
Comment (erickzanardo) [inline packages/shorebird_cli/lib/src/commands/patch/patch_command.dart]: @bryanoltman I was on the fence when choosing the code here, I ended up returning success because this is an expected error, but I wonder if `usage` would be more fitting, since in a way, the command was used wrongly?

Comment (bryanoltman) [reply packages/shorebird_cli/lib/src/commands/patch/patch_command.dart]: `usage` sounds like a better option.

File: packages/shorebird_cli/test/src/commands/patch/patch_command_test.dart [hunk 2]
```diff
@@ -678,6 +678,26 @@ void main() {
         );
       });
 
+      group('when prompting for releases, but there is none', () {
+        setUp(() {
+          when(
+            () => codePushClientWrapper.getReleases(appId: any(named: 'appId')),
+          ).thenAnswer((_) async => []);
+        });
+        test('warns and exits', () async {
```
Comment (bryanoltman) [inline packages/shorebird_cli/test/src/commands/patch/patch_command_test.dart]:
```suggestion
          ).thenAnswer((_) async => []);
        }); 

        test('warns and exits', () async {
```

**Review by bryanoltman — APPROVED** [review]
LGTM with comments
