### PR TITLE
fix(shorebird_cli): don't check for flavors in flutter module

### LINKED ISSUE #985: fix: Can't run add_to_app example
Can't run after checkout:
```
PS C:\Users\micro\Documents\GitHub\samples\add_to_app\my_flutter_module> shorebird release aar --release-version 1.2.3+1
✓ Fetching apps (0.3s)
Could not find app with id: "9821ce65-8e67-47d8-9783-13b910412f8c".
This app may not exist or you may not have permission to view it.
```

So have to `rm shorebird.yaml`, except then can't `shorebird init`:

```
PS C:\Users\micro\Documents\GitHub\samples\add_to_app\my_flutter_module> shorebird init
✗ Detecting product flavors (14ms)
Unable to extract product flavors.
Could not find .android\gradlew.bat.
Make sure you have run "flutter build apk" at least once.
```

### PR DESCRIPTION
**Pull request by bryanoltman**
## Description

Because flavors aren't supported in flutter modules, don't try to read them from the bundled (potentially missing) android project.

Fixes https://github.com/shorebirdtech/shorebird/issues/985

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

File: packages/shorebird_cli/lib/src/gradlew.dart [hunk 1]
```diff
@@ -60,12 +60,11 @@ class Gradlew {
     final javaHome = java.home;
     // Flutter apps have android files in root/android
     // Flutter modules have android files in root/.android
-    final androidRoot = [
-      Directory(p.join(projectPath, 'android')),
-      Directory(p.join(projectPath, '.android')),
-    ].firstWhereOrNull((dir) => dir.existsSync());
+    final androidRoot = Directory(p.join(projectPath, 'android'));
```
Comment (felangel) [inline packages/shorebird_cli/lib/src/gradlew.dart:61]: Do we want to change this logic? Or should we just handle this explicitly in `shorebird init`?

Comment (bryanoltman) [reply packages/shorebird_cli/lib/src/gradlew.dart:61]: Discussed offline – keeping the change here

File: packages/shorebird_cli/lib/src/gradlew.dart [hunk 2]
```diff
@@ -60,12 +60,11 @@ class Gradlew {
     final javaHome = java.home;
     // Flutter apps have android files in root/android
     // Flutter modules have android files in root/.android
```
Comment (felangel) [inline packages/shorebird_cli/lib/src/gradlew.dart]:
```suggestion
```

**Review by felangel — APPROVED** [review]
