### PR TITLE
fix: cache clear command was breaking

### LINKED ISSUE #2233: fix:  shorebird cache clean  fails with log file not found
**Description**

When trying to run `shorebird cache clean` we get the following error:

```
✗ Failed to delete cache directory /Users/erick/projects/shorebird/shorebird/bin/cache: FileSystemException: Deletion failed, path = '/Users/erick/Library/Application Support/shorebird/logs' (OS Error: Directory not empty, errno = 66) (0.8s)
```

This is mostly likely happening because we delete the log file in this command, but tries to log to it to show the completed progress.

Also reported at https://github.com/shorebirdtech/shorebird/issues/2231

**Steps To Reproduce**

1. run `shorebird cache clean`
2. see erro

**Expected Behavior**

`shorebird cache clean` should no fail with error

### PR DESCRIPTION
**Pull request by erickzanardo**
## Description

The cache clean command would fail because it were deleting the log file, and trying to log right after.

Fixes #2233 

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore
- [ ] 🧪 Tests

### CODE REVIEW

File: packages/shorebird_cli/lib/src/logger.dart [hunk 1]
```diff
@@ -42,6 +42,11 @@ void _writeToLogFile(Object? message, {required File logFile}) {
     return;
   }
 
+  // Making sure the log file exists before writing to it.
+  // This is necessary because the log file may be deleted by a cache
+  // clear command.
+  if (!logFile.existsSync()) return;
```
Comment (erickzanardo) [inline packages/shorebird_cli/lib/src/logger.dart]: My reasoning on this: The file should always be there, since it is created upon initialization. So if it is not there, that means that we shouldn't log, i.g. on the cache clear commando I don't think we should recreate the file that we just created.

Lmk if you all think that this makes sense or if you can think in a better approach.

File: packages/shorebird_cli/integration_test/helpers.dart [hunk 2]
```diff
@@ -0,0 +1,20 @@
+import 'dart:io';
+
+import 'package:mason_logger/mason_logger.dart';
+
+ProcessResult runCommand(
```
Comment (bryanoltman) [inline packages/shorebird_cli/integration_test/helpers.dart:9]: Docs for this function (usage, what it does beyond invoking `Process.run`) would be helpful

File: packages/shorebird_cli/lib/src/logger.dart (hunk 1 above)
Comment (bryanoltman) [reply packages/shorebird_cli/lib/src/logger.dart]: I don't know that I'm convinced that `cache clear` should delete logs. Maybe that's a cleaner solution? I worry this might put us in a silent failure scenario.

Comment (erickzanardo) [reply packages/shorebird_cli/lib/src/logger.dart]: humm, yeah, that is a good argument! logs are not cache! I am gonna instead remove the log clearing call from the command then!

Comment (erickzanardo) [reply packages/shorebird_cli/lib/src/logger.dart]: Updated, lmk wdyt!

**Review by bryanoltman — APPROVED** [review]
