### PR TITLE
fix(shorebirdl_cli): add stamp file to cache artifacts to mark successful download

### LINKED ISSUE #1771: fix: validate integrity of aot_tools.dill asset on disk
From discord:
https://discord.com/channels/1030243211995791380/1030243213002412164/1213550586134265886

```
⠋ Linking AOT files...[Process.run] /Users/james/.shorebird/bin/cache/flutter/5b9d29d67adb059103beefb65710ee3dabae2f85/bin/dart run /Users/james/.shorebird/bin/cache/artifacts/aot-tools/62fa4e8bb30f56eb658989d3e6a982cb787d79d6/aot-tools.dill link --base=/var/folders/tq/pd1qk95j1hs9gfr8yws2m47w0000gn/T/TOpybX/Products/Applications/Runner.app/Frameworks/App.framework/App --patch=/Users/james/development/project/sport_mobile/build/out.aot --analyze-snapshot=/Users/james/.shorebird/bin/cache/flutter/5b9d29d67adb059103beefb65710ee3dabae2f85/bin/cache/artifacts/engine/ios-release/analyze_snapshot_arm64 --output=/Users/james/development/project/sport_mobile/build/out.vmcode (in /Users/james/development/project/sport_mobile/build)
Exited with code 253

stderr:
Can't load Kernel binary: Invalid kernel binary: Indicated size is invalid.

[2K
✗ Failed to link AOT files: Exception: Failed to link: Can't load Kernel binary: Invalid kernel binary: Indicated size is invalid.
 (0.1s)
```

Why is dart pulling from 5b9d29d67adb059103beefb65710ee3dabae2f85 but aot-tools pulling from 62fa4e8bb30f56eb658989d3e6a982cb787d79d6?

https://github.com/shorebirdtech/engine/commit/62fa4e8bb30f56eb658989d3e6a982cb787d79d6

That appears to be Dart 3.3.0, which is the same one used by Flutter 3.19.2.

/Users/james/.shorebird/bin/cache/flutter/5b9d29d67adb059103beefb65710ee3dabae2f85/bin/dart --version
Dart SDK version: 3.3.0 (stable) (Tue Feb 13 10:25:19 2024 +0000) on "macos_arm64"

### PR DESCRIPTION
**Pull request by bryanoltman**
## Description

Updates our cache management to write a zero-byte stamp file alongside the cache artifact when an artifact has successfully been downloaded and (optionally) extracted. We check for the existence of this file when determining that an artifact is valid. If this file does not exist, the artifact will be redownloaded.

Fixes https://github.com/shorebirdtech/shorebird/issues/1771

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore
- [ ] 🧪 Tests

### CODE REVIEW

**Review by erickzanardo — APPROVED** [review]

File: packages/shorebird_cli/lib/src/cache.dart [hunk 1]
```diff
@@ -154,11 +154,15 @@ abstract class CachedArtifact {
     return stream.pipe(file.openWrite());
   }
 
+  /// The artifact file on disk.
   File get file =>
       File(p.join(cache.getArtifactDirectory(fileName).path, fileName));
 
+  /// Used to validate that the artifact was fully downloaded and extracted.
+  File get stampFile => File('${file.path}.stamp');
```
Comment (felangel) [inline packages/shorebird_cli/lib/src/cache.dart:162]: Minor but I was under the impression that a stamp file was conventionally used to maintain a timestamp. Maybe there’s a better name here?

Comment (bryanoltman) [reply packages/shorebird_cli/lib/src/cache.dart:162]: Yeah, I was uncertain about this. I could write a timestamp to this file, but it seems a bit silly to do so if we never use it for anything.

File: packages/shorebird_cli/lib/src/cache.dart [hunk 2]
```diff
@@ -173,6 +177,11 @@ abstract class CachedArtifact {
   }
 
   Future<void> update() async {
+    // Clear any existing artifact files.
+    if (file.parent.existsSync()) {
+      await file.parent.delete(recursive: true);
```
Comment (felangel) [inline packages/shorebird_cli/lib/src/cache.dart]: Any reason why we're using `delete` (async) instead of `deleteSync`?

File: packages/shorebird_cli/lib/src/cache.dart (hunk 1 above)
Comment (eseidel) [reply packages/shorebird_cli/lib/src/cache.dart:162]: Looks like ninja stamp files are empty too.  It's just a "we finished task X" is all it's marking.  Then when you next wonder if you should run task X you can check to see last time it was finished and compare if it's inputs (in this case, presumably just the version of flutter or version of shorebird has changed since that time?

**Review by eseidel — APPROVED** [review]
Confirming, this is going to cause all customers to re-download all artifacts, correct?

File: packages/shorebird_cli/lib/src/cache.dart [hunk 3]
```diff
@@ -173,6 +177,11 @@ abstract class CachedArtifact {
   }
 
   Future<void> update() async {
+    // Clear any existing artifact files.
+    if (file.parent.existsSync()) {
```
Comment (felangel) [inline packages/shorebird_cli/lib/src/cache.dart]: Do we want to delete the entire parent directory? This is assuming that each artifact will be cached in its own nested directory (which I'm not sure is a valid assumption) 🤷 ?

**Comment by eseidel** [comment]
Do we need to have any extra caution around deleting directories? (e.g. making sure they're under the cache?)

File: packages/shorebird_cli/lib/src/cache.dart (hunk 1 above)
Comment (felangel) [reply packages/shorebird_cli/lib/src/cache.dart:162]: Eric looked and said ninja does something similar so seems reasonable to me 👍

**Review by felangel — APPROVED** [review]

File: packages/shorebird_cli/lib/src/cache.dart (hunk 2 above)
Comment (bryanoltman) [reply packages/shorebird_cli/lib/src/cache.dart]: If this takes any amount of time, the async option makes sure any progress indicators or other updates don't lock up

File: packages/shorebird_cli/lib/src/cache.dart (hunk 3 above)
Comment (bryanoltman) [reply packages/shorebird_cli/lib/src/cache.dart]: Updated to only delete the artifact and stamp file.
