### PR TITLE
fix(shorebird_cli): refer to https://console.shorebird.dev for account creation

### LINKED ISSUE #1234: fix: using `shorebird login` with an account that does not exist suggests to use `shorebird account create`
**Description**

When using `shorebird login` and logging with an account that does not exist, you get the following error message:

```
$ shorebird login
The Shorebird CLI needs your authorization to manage apps, releases, and patches on your behalf.

In a browser, visit this URL to log in:

https://accounts.google.com/o/oauth2/v2/auth?...

Waiting for your authorization...
We could not find a Shorebird account for [EMAIL].
If you have not yet created an account, you can do so by running "shorebird account create". If you believe this is an error, please reach out to us via Discord, we're happy to help!
```

However, the command `shorebird account create` does not exist anymore:

```
$ shorebird account create
Could not find a subcommand named "create" for "shorebird account".
```

**Steps To Reproduce**

1. Enter `shorebird login`
2. Use a Google account that is not a Shorebird account yet
3. See error

**Expected Behavior**

It would suggest me a way that works, like using the web.

**Screenshots**

No screenshots.

**Additional Context**

```
$ shorebird --version
Shorebird 0.14.6 • git@github.com:shorebirdtech/shorebird.git
Flutter 3.13.2 • revision 9486b6431e6c808c4e131f134b5d88017b3c32ab
Engine • revision e7bdf38443dff65d64446d6ca4074a35a587c770
```

### PR DESCRIPTION
**Pull request by nilsreichardt**
## Description

The CLI suggested using `shorebird account create` to create an account if no account could be found. However, since version 0.11.0, there is no `shorebird account create` anymore. I replaced `shorebird account create` with "https://console.shorebird.dev" to create an account. 

Fixes #1234 (lol, nice ticket number)

(I don't know if this is the correct fix, feel free to close this PR)

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Review by felangel — APPROVED** [review]

File: packages/shorebird_cli/lib/src/commands/login_ci_command.dart [hunk 1]
```diff
@@ -28,7 +28,7 @@ class LoginCiCommand extends ShorebirdCommand {
 We could not find a Shorebird account for ${error.email}.''',
         )
         ..info(
-          """If you have not yet created an account, you can do so by running "${lightCyan.wrap('shorebird account create')}". If you believe this is an error, please reach out to us via Discord, we're happy to help!""",
+          """If you have not yet created an account, you can go to "${lightCyan.wrap('https://console.shorebird.dev')}" create on. If you believe this is an error, please reach out to us via Discord, we're happy to help!""",
```
Comment (felangel) [inline packages/shorebird_cli/lib/src/commands/login_ci_command.dart]:
```suggestion
          """If you have not yet created an account, go to "${lightCyan.wrap('https://console.shorebird.dev')}" to create one. If you believe this is an error, please reach out to us via Discord, we're happy to help!""",
```
