### PR TITLE
fix: improve handling of CI tokens

### LINKED ISSUE #2846: fix: invalid SHOREBIRD_TOKEN produces confusing error
From a user via discord:
https://discord.com/channels/1030243211995791380/1336312156018315315/1336312156018315315

```
shorebird release ios  --verbose  --target ./lib/main_stage.dart --flutter-version=3.24.3 -- --export-options-plist ios/ExportOptions.plist
FormatException: Unexpected end of input (at character 1)
^
#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1465:5)
#1      _ChunkedJsonParser.close (dart:convert-patch/convert_patch.dart:499:7)
#2      _parseJson (dart:convert-patch/convert_patch.dart:37:10)
#3      JsonDecoder.convert (dart:convert/json.dart:610:36)
#4      JsonCodec.decode (dart:convert/json.dart:216:41)
#5      jsonDecode (dart:convert/json.dart:155:10)
#6      new CiToken.fromBase64 (package:shorebird_cli/src/auth/ci_token.dart:19:7)
#7      Auth._loadCredentials (package:shorebird_cli/src/auth/auth.dart:319:24)
#8      new Auth (package:shorebird_cli/src/auth/auth.dart:193:5)
#9      ScopedRef._value (package:scoped_deps/src/scoped_deps.dart:19:32)
#10     ScopedRef._value (package:scoped_deps/src/scoped_deps.dart)
#11     read (package:scoped_deps/src/scoped_deps.dart:47:60)
#12     auth (package:shorebird_cli/src/auth/auth.dart:31:18)
#13     ShorebirdValidator.validatePreconditions (package:shorebird_cli/src/shorebird_validator.dart:73:38)
#14     IosReleaser.assertPreconditions (package:shorebird_cli/src/commands/release/ios_releaser.dart:72:32)
#15     ReleaseCommand.createRelease (package:shorebird_cli/src/commands/release/release_command.dart:219:20)
#16     MappedListIterable.elementAt (dart:_internal/iterable.dart:425:31)
#17     ListIterator.moveNext (dart:_internal/iterable.dart:354:26)
#18     ReleaseCommand.run (package:shorebird_cli/src/commands/release/release_command.dart:159:26)
#19     CommandRunner.runCommand (package:args/command_runner.dart:212:27)
#20     CompletionCommandRunner.runCommand (package:cli_completion/src/command_runner/completion_command_runner.dart:89:18)
#21     ShorebirdCliCommandRunner.runCommand (package:shorebird_cli/src/shorebird_cli_command_runner.dart:201:32)
#22     ShorebirdCliCommandRunner.run.<anonymous closure> (package:shorebird_cli/src/shorebird_cli_command_runner.dart:128:19)
#23     _rootRun (dart:async/zone.dart:1399:13)
#24     _CustomZone.run (dart:async/zone.dart:1301:19)
#25     _runZoned (dart:async/zone.dart:1826:10)
#26     runZoned (dart:async/zone.dart:1763:10)
#27     runScoped (package:scoped_deps/src/scoped_deps.dart:64:10)
#28     ShorebirdCliCommandRunner.run (package:shorebird_cli/src/shorebird_cli_command_runner.dart:127:20)
#29     main.<anonymous closure>.<anonymous closure> (file:///Users/admin/.shorebird/packages/shorebird_cli/bin/shorebird.dart:41:49)
#30     _rootRun (dart:async/zone.dart:1399:13)
#31     _CustomZone.run (dart:async/zone.dart:1301:19)
#32     _runZoned (dart:async/zone.dart:1826:10)
#33     runZoned (dart:async/zone.dart:1763:10)
#34     runScoped (package:scoped_deps/src/scoped_deps.dart:64:10)
#35     main.<anonymous closure> (file:///Users/admin/.shorebird/packages/shorebird_cli/bin/shorebird.dart:40:13)
#36     _rootRun (dart:async/zone.dart:1399:13)
#37     _CustomZone.run (dart:async/zone.dart:1301:19)
#38     _runZoned (dart:async/zone.dart:1826:10)
#39     runZoned (dart:async/zone.dart:1763:10)
#40     IOOverrides.runZoned (dart:io/overrides.dart:146:10)
#41     main (file:///Users/admin/.shorebird/packages/shorebird_cli/bin/shorebird.dart:38:21)
#42     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:33)
#43     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
[Process.run] git symbolic-ref HEAD (in /Users/admin/.shorebird/bin/cache)
Exited with code 0
stdout:
refs/heads/stable
[Process.run] git rev-parse --verify HEAD (in /Users/admin/.shorebird/bin/cache)
Exited with code 0
stdout:
a1dfc7d6bb8a2c425998eb5decf36969ba814752
[Process.run] git remote prune origin (in /Users/admin/.shorebird/bin/cache)
Exited with code 0
[Process.run] git fetch --tags (in /Users/admin/.shorebird/bin/cache)
Exited with code 0
[Process.run] git rev-parse --verify @{upstream} (in /Users/admin/.shorebird/bin/cache)
Exited with code 0
stdout:
0633510ab27617b8d486c27b328169509cc57042
```

We should be catching the FormatError and explaining that it's a SHOREBIRD_TOKEN parse error.

### PR DESCRIPTION
**Pull request by bryanoltman**
## Description

Adds a more friendly error message when `SHOREBIRD_TOKEN` is malformed, and more gracefully handles trailing and leading whitespace.

Fixes https://github.com/shorebirdtech/shorebird/issues/2846

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore
- [ ] 🧪 Tests

### CODE REVIEW

File: packages/shorebird_cli/lib/src/auth/auth.dart [hunk 1]
```diff
@@ -315,7 +315,19 @@ class Auth {
...
     final envToken = platform.environment[shorebirdTokenEnvVar];
     if (envToken != null) {
-      _token = CiToken.fromBase64(envToken);
+      try {
+        _token = CiToken.fromBase64(envToken.trim());
+      } on FormatException catch (e) {
+        logger
+          ..err(
+            '''
+Failed to parse CI token from environment. This likely means that your CI token is incorrectly formatted.
```
Comment (eseidel) [inline packages/shorebird_cli/lib/src/auth/auth.dart:324]: Should this say shorebirdTokenEnvVar or similar in the output?

**Review by eseidel — APPROVED** [review]

File: packages/shorebird_cli/lib/src/auth/auth.dart (hunk 1 above)
Comment (bryanoltman) [reply packages/shorebird_cli/lib/src/auth/auth.dart:324]: It could but that seems unnecessary–we only print this if we detect the environment variable

Comment (bryanoltman) [reply packages/shorebird_cli/lib/src/auth/auth.dart:324]: We also do mention the variable name on the next line

Comment (eseidel) [reply packages/shorebird_cli/lib/src/auth/auth.dart:324]: sg.  Just the person reading that message might not know what the env variable is 🤷

**Comment by eseidel** [comment]
Thanks!
