### PR TITLE
fix(shorebird_cli): use aot-tools.dill for linking if available

### LINKED ISSUE #1595: fix: shorebird doesn't work on mac x64 machines
**Description**

Just got started with Shorebird today. `shorebird release iOS-alpha` worked fine, but `shorebird patch iOS-alpha` gave an error: Failed to link AOT files: ProcessException: Bad CPU type in executable.

See screenshots for the entire response and result from shorebird doctor.

**Screenshots**

repsonse
doctor

### PR DESCRIPTION
**Pull request by bryanoltman**
## Description

Because the precompiled `aot-tools` executable will only work on architectures that match the `dart` executable used to build it, and because we build dart on arm64 macs, the `aot-tools` executable does not work on x64 macs. This change looks for an aot-tools kernel file (`.dill`) and uses the `dart` packaged with shorebird's flutter (which was used to produce the kernel file) to run it.

Fixes https://github.com/shorebirdtech/shorebird/issues/1595

Related to but not dependent on https://github.com/shorebirdtech/_build_engine/pull/56

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

File: packages/shorebird_cli/lib/src/cache.dart [hunk 1]
```diff
@@ -179,9 +180,7 @@ allowed to access $storageUrl.''',
 
     await extractArtifact(response.stream, location.path);
 
-    if (platform.isWindows) return;
-
-    for (final executable in executables) {
+    if (!platform.isWindows) {
       final result = await process.start(
         'chmod',
         ['+x', p.join(location.path, executable)],
```
Comment (eseidel) [inline packages/shorebird_cli/lib/src/cache.dart]: lol.  So I guess we're making the .dill executable? :)

**Review by eseidel — APPROVED** [review]

File: packages/shorebird_cli/lib/src/cache.dart (hunk 1 above)
Comment (bryanoltman) [reply packages/shorebird_cli/lib/src/cache.dart]: ¯\_(ツ)_/¯ seemed fine, but I added an `isExecutable` property to `CachedArtifact` so only those are now made to be executable.

Comment (eseidel) [reply packages/shorebird_cli/lib/src/cache.dart]: Yeah was fine, mostly amused.

**Review by eseidel — APPROVED** [review]

File: packages/shorebird_cli/lib/src/cache.dart [hunk 2]
```diff
@@ -198,7 +199,10 @@ class AotToolsArtifact extends CachedArtifact {
   String get name => 'aot-tools';
```
Comment (felangel) [inline packages/shorebird_cli/lib/src/cache.dart:199]: Should we rename this to executableName to avoid confusion? I don't think it's obvious what the difference between name and fileName is at first glance.

File: packages/shorebird_cli/lib/src/cache.dart [hunk 3]
```diff
@@ -198,7 +199,10 @@ class AotToolsArtifact extends CachedArtifact {
...
 
   @override
-  List<String> get executables => ['aot-tools'];
+  String get fileName => 'aot-tools.dill';
```
Comment (felangel) [inline packages/shorebird_cli/lib/src/cache.dart:202]: Why couldn't we change `name` to be `aot-tools.dill` and avoid introducing a new `fileName`?

File: packages/shorebird_cli/lib/src/cache.dart [hunk 4]
```diff
@@ -213,18 +217,8 @@ class AotToolsArtifact extends CachedArtifact {
...
-    } else if (platform.isLinux) {
-      artifactName += 'linux-x64';
-    } else if (platform.isWindows) {
-      artifactName += 'windows-x64';
-    }
-
-    return '${cache.storageBaseUrl}/${cache.storageBucket}/shorebird/${shorebirdEnv.shorebirdEngineRevision}/$artifactName';
-  }
+  String get storageUrl =>
+      '${cache.storageBaseUrl}/${cache.storageBucket}/shorebird/${shorebirdEnv.shorebirdEngineRevision}/aot-tools.dill';
```
Comment (felangel) [inline packages/shorebird_cli/lib/src/cache.dart:221]: Could this use `fileName` instead of the string literal `aot-tools.dill`?

File: packages/shorebird_cli/lib/src/cache.dart (hunk 3 above)
Comment (bryanoltman) [reply packages/shorebird_cli/lib/src/cache.dart:202]: Because the artifact path is `[name]/[fileName]` (or, in the case of aot-tools, `[name]/[flutterRev]/[fileName]`). We could use fileName for both, but this felt cleaner.

File: packages/shorebird_cli/lib/src/cache.dart (hunk 4 above)
Comment (bryanoltman) [reply packages/shorebird_cli/lib/src/cache.dart:221]: We could ¯\_(ツ)_/¯

File: packages/shorebird_cli/lib/src/cache.dart (hunk 2 above)
Comment (bryanoltman) [reply packages/shorebird_cli/lib/src/cache.dart:199]: I can add some comments. I changed `executables` to `executable` (because our artifacts only ever have one file) to `fileName` (because our artifacts aren't always executable).
