### PR TITLE
fix(shorebird_cli): don't run `flutter pub get` after build if flutter is not installed

### LINKED ISSUE #1430: "`flutter pub get` failed to run after the build completed" prints if Flutter is not installed
This is sometimes an issue on CI. We shouldn't attempt to run this command if Flutter is not installed.

### PR DESCRIPTION
**Pull request by bryanoltman**
## Description

Checks for the presence of flutter on the user's path before attempting to run `flutter pub get` after a build.

For context: `flutter pub get` is run after a build to reset `.dart_tool/package_config.json` to point to the system flutter install instead of the shorebird flutter install. This value is set when running a flutter build command or flutter pub get.

Fixes https://github.com/shorebirdtech/shorebird/issues/1430

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

File: packages/shorebird_cli/lib/src/shorebird_build_mixin.dart [hunk 1]
```diff
@@ -277,6 +278,12 @@ mixin ShorebirdBuildMixin on ShorebirdCommand {
   /// https://github.com/shorebirdtech/shorebird/issues/1101 for more info.
   Future<void> _systemFlutterPubGet() async {
     const executable = 'flutter';
+    if (osInterface.which(executable) == null) {
```
Comment (felangel) [inline packages/shorebird_cli/lib/src/shorebird_build_mixin.dart:281]: we really need to get rid of this mixin so we can avoid having to duplicate the tests 🤣

**Review by felangel — APPROVED** [review]

File: packages/shorebird_cli/lib/src/shorebird_build_mixin.dart (hunk 1 above)
Comment (bryanoltman) [reply packages/shorebird_cli/lib/src/shorebird_build_mixin.dart:281]: Yeah, this PR is a case study re: why we shouldn't use mixins for any functionality we want to test :)
