### PR TITLE
fix(shorebird_cli): `shorebird preview` to not use outdated cached preview artifacts

### LINKED ISSUE #1746: Build does not update if you delete a release and then upload new one with same version number
App ID: 130984c0-a89c-44a0-972b-f29f9725b216

**Description**

I have a shorebird release for android with version number 1.1.55+73 which is good for use. So far, so good. 

However, i am having some platform specific difficulty with my IOS version of that release. Because i want my Android and IOS build numbers to be consistent, my working flow whilst fixing/investigating my IOS issues is to 

1. delete the IOS build from that release (which i want to keep because the android version works)
2. create a fixed IOS build with the same version/release number

However, when i do this.. the edits to the IOS build in subsequent submissions are NOT reflected when i run previews.

For example, i added some print logs to help me debug, but when i run preview after i released those changes, i was still seeing the OLD print logs when i run preview. 

So it's as if the old original build i thought i had deleted is actually retained and never overwritten

**Steps To Reproduce**

1. Create a release on both Android and IOS
2. From the shorebird console, delete the IOS version of that release
3. Change some code and create a NEW IOS release with the same version number 

**Expected Behavior**

I would expect the code changes to be reflected when i run preview

### PR DESCRIPTION
**Pull request by erickzanardo**
## Description

When running a preview, the CLI will always use the cache artifact if one if found. This might make the command run an outdated artifact when a release is delete by some reason.

This PR makes the artifact id to be part of the path of the preview artifact, that way, if a release is deleted and recreated, the id will be a fresh one and the cli will not accidentally use the wrong cached artifact.

Fixes https://github.com/shorebirdtech/shorebird/issues/1746

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore
- [ ] 🧪 Tests

### CODE REVIEW

File: packages/shorebird_cli/lib/src/commands/preview_command.dart [hunk 1]
```diff
@@ -213,41 +213,54 @@ class PreviewCommand extends ShorebirdCommand {
     String? deviceId,
   }) async {
     const platform = ReleasePlatform.android;
-    final aabFile = File(
-      getArtifactPath(
+
+    final downloadArtifactProgress = logger.progress('Downloading release');
+    late File aabFile;
+    late ReleaseArtifact artifact;
```
Comment (bryanoltman) [inline packages/shorebird_cli/lib/src/commands/preview_command.dart]:
```suggestion
    late ReleaseArtifact releaseAabArtifact;
```

File: packages/shorebird_cli/test/src/commands/preview_command_test.dart [hunk 2]
```diff
@@ -915,6 +917,28 @@ channel: ${track.channel}
...
+          when(
+            () => codePushClientWrapper.getReleaseArtifact(
+              appId: any(named: 'appId'),
+              releaseId: any(named: 'releaseId'),
+              arch: any(named: 'arch'),
+              platform: any(named: 'platform'),
+            ),
+          ).thenThrow(Exception('oops'));
+        });
+        test('returns error and logs', () async {
```
Comment (felangel) [inline packages/shorebird_cli/test/src/commands/preview_command_test.dart]:
```suggestion
        });

        test('returns error and logs', () async {
```
nit newline

File: packages/shorebird_cli/test/src/commands/preview_command_test.dart [hunk 3]
```diff
@@ -1202,6 +1226,34 @@ channel: ${DeploymentTrack.staging.channel}
...
```
Comment (felangel) [inline packages/shorebird_cli/test/src/commands/preview_command_test.dart]:
```suggestion
        });

        test('returns error and logs', () async {
```
nit newline

**Review by bryanoltman — APPROVED** [review]

**Review by felangel — APPROVED** [review]
LGTM ✅
