### PR TITLE
fix(shorebird_cli): run all release and patch commands with a scoped shorebirdEnv

### LINKED ISSUE #1794: fix: shorebird patch fails when switching flutter revisions
**Description**

Running `shorebird patch ios` for a release that was built using an older flutter revision fails due to:

```
[WARN] iOS support is beta. Some apps may run slower after patching.
See ]8;;https://docs.shorebird.dev/status\https://docs.shorebird.dev/status]8;;\ for more information.
⠋ Fetching apps...
✓ Fetching apps (0.3s)
⠋ Building patch...
✓ Building patch (190.2s)
Detected release version 2.0.0+02000
⠋ Fetching releases...
✓ Fetching releases (99ms)

The release you are trying to patch was built with a different version of Flutter.

Release Flutter Revision: 771d07b2cf97cf107bae6eeedcf41bdc9db772fa
Current Flutter Revision: 5b9d29d67adb059103beefb65710ee3dabae2f85

⠋ Building patch...⠋ Switching to Flutter revision 771d07b2cf97cf107bae6eeedcf41bdc9db772fa...
✓ Switching to Flutter revision 771d07b2cf97cf107bae6eeedcf41bdc9db772fa (7.4s)
⠋ Switching back to original Flutter revision 5b9d29d67adb059103beefb65710ee3dabae2f85...
✓ Switching back to original Flutter revision 5b9d29d67adb059103beefb65710ee3dabae2f85 (4ms)

✗ Exception: Failed to create snapshot: Can't load Kernel binary: Invalid kernel binary format version.
 (163.1s)


Build failed :|
Step 7 script `🚀 Shorebird Patch` exited with status code 70
```

I suspect the issue is we're not using the correct Flutter revision when executing `gen_snapshot` because `ShorebirdArtifacts` uses `ShorebirdEnv` to resolve the artifact and in this case we're building using a flutter revision override which isn't propagating when building the snapshot.

`buildElfAotSnapshot` likely also needs to take a `flutterRevision` and do the correct lookup similar to how `buildIpa` was modified to require a specific `flutterRevision`.

Tagging @bryanoltman since it's related to #1790 (which looks like it was an incomplete fix).

### PR DESCRIPTION
**Pull request by bryanoltman**
## Description

Updates all patch and release commands to run build operations with a scoped `shorebirdEnv`, which is used to determine the current Flutter revision.

The diff is ugly, but broadly, this change simply creates a new `shorebirdEnv` using `copyWith` once we know which Flutter revision we're using to create the build, and wraps all build operations in `runScoped` with that shorebirdEnv as an override.

Fixes https://github.com/shorebirdtech/shorebird/issues/1794

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

File: packages/shorebird_cli/lib/src/commands/release/release_android_command.dart [hunk 1]
```diff
@@ -139,162 +140,165 @@ Use `shorebird flutter versions list` to list available versions.
...
-    if (switchFlutterRevision) {
-      await shorebirdFlutter.useRevision(revision: flutterRevisionForRelease);
-    }
-
-    final flutterVersionString = await shorebirdFlutter.getVersionAndRevision();
-
-    final buildProgress = logger.progress(
-      'Building release with Flutter $flutterVersionString',
+    final flutterInstallProgress = logger.progress(
+      'Installing Flutter $flutterRevisionForRelease',
```
Comment (felangel) [inline packages/shorebird_cli/lib/src/commands/release/release_android_command.dart]: So do we always show this log even when the revision of flutter is already installed?

File: packages/shorebird_cli/lib/src/commands/release/release_android_command.dart [hunk 2]
```diff
@@ -139,162 +140,165 @@ Use `shorebird flutter versions list` to list available versions.
...
     );
+    await shorebirdFlutter.installRevision(revision: flutterRevisionForRelease);
+    flutterInstallProgress.complete();
```
Comment (felangel) [inline packages/shorebird_cli/lib/src/commands/release/release_android_command.dart]: Minor but if `installRevision` throws, then the progress will never complete which will look a bit weird to users.

File: packages/shorebird_cli/lib/src/commands/release/release_android_command.dart [hunk 3]
```diff
@@ -139,162 +140,165 @@ Use `shorebird flutter versions list` to list available versions.
...
-        flutterRevisionForRelease != originalFlutterRevision;
-
-    if (switchFlutterRevision) {
-      await shorebirdFlutter.useRevision(revision: flutterRevisionForRelease);
-    }
-
-    final flutterVersionString = await shorebirdFlutter.getVersionAndRevision();
-
-    final buildProgress = logger.progress(
-      'Building release with Flutter $flutterVersionString',
```
Comment (felangel) [inline packages/shorebird_cli/lib/src/commands/release/release_android_command.dart:153]: It was nice to have this log framed as `"Building with Flutter <revision>"` instead of `installing Flutter` since we don't always need to install a revision of Flutter right? Most times, the revision they use will be default version that is already installed. I think it would be nice to keep the old copy wdyt?

File: packages/shorebird_cli/test/src/commands/release/release_aar_command_test.dart [hunk 4]
```diff
@@ -336,22 +351,26 @@ $exception''',
...
-            'and reverts to original flutter version', () async {
+        test('uses specified flutter version to build', () async {
           setUpProjectRootArtifacts();
+          when(
+            () => shorebirdProcess.run(
+              any(),
+              any(that: containsAll(['build', 'aar'])),
+              runInShell: any(named: 'runInShell'),
+            ),
+          ).thenAnswer((invocation) async {
```
Comment (felangel) [inline packages/shorebird_cli/test/src/commands/release/release_aar_command_test.dart]:
```suggestion
          ).thenAnswer((_) async {
```

File: packages/shorebird_cli/test/src/commands/release/release_android_command_test.dart [hunk 5]
```diff
@@ -136,6 +136,16 @@ void main() {
       shorebirdValidator = MockShorebirdValidator();
 
       when(() => shorebirdEnv.getShorebirdYaml()).thenReturn(shorebirdYaml);
+      when(
+        () => shorebirdEnv.copyWith(
+          flutterRevisionOverride: any(named: 'flutterRevisionOverride'),
+        ),
+      ).thenAnswer((invocation) {
```
Comment (felangel) [inline packages/shorebird_cli/test/src/commands/release/release_android_command_test.dart:143]:
```suggestion
      ).thenAnswer((_) {
```

File: packages/shorebird_cli/test/src/commands/release/release_ios_command_test.dart [hunk 6]
```diff
@@ -211,9 +211,24 @@ flutter:
       ).thenReturn(projectRoot);
       when(() => shorebirdEnv.flutterRevision).thenReturn(flutterRevision);
       when(() => shorebirdEnv.isRunningOnCI).thenReturn(false);
+      when(
+        () => shorebirdEnv.copyWith(
+          flutterRevisionOverride: any(named: 'flutterRevisionOverride'),
+        ),
+      ).thenAnswer((invocation) {
```
Comment (felangel) [inline packages/shorebird_cli/test/src/commands/release/release_ios_command_test.dart:218]:
```suggestion
      ).thenAnswer((_) {
```

**Review by felangel — APPROVED** [review]

File: packages/shorebird_cli/test/src/commands/release/release_aar_command_test.dart (hunk 4 above)
Comment (bryanoltman) [reply packages/shorebird_cli/test/src/commands/release/release_aar_command_test.dart]: Done

File: packages/shorebird_cli/lib/src/commands/release/release_android_command.dart (hunk 3 above)
Comment (bryanoltman) [reply packages/shorebird_cli/lib/src/commands/release/release_android_command.dart:153]: We print both "installing" and "building", the diff is just bad.

File: packages/shorebird_cli/lib/src/commands/release/release_android_command.dart (hunk 1 above)
Comment (bryanoltman) [reply packages/shorebird_cli/lib/src/commands/release/release_android_command.dart]: Yep, but I'll fix that and add error handling for install failures. One sec.

File: packages/shorebird_cli/lib/src/commands/release/release_android_command.dart (hunk 2 above)
Comment (bryanoltman) [reply packages/shorebird_cli/lib/src/commands/release/release_android_command.dart]: On it

File: packages/shorebird_cli/lib/src/commands/release/release_android_command.dart (hunk 1 above)
Comment (bryanoltman) [reply packages/shorebird_cli/lib/src/commands/release/release_android_command.dart]: Updated

File: packages/shorebird_cli/lib/src/commands/release/release_android_command.dart (hunk 2 above)
Comment (bryanoltman) [reply packages/shorebird_cli/lib/src/commands/release/release_android_command.dart]: Fixed

File: packages/shorebird_cli/lib/src/shorebird_flutter.dart [hunk 7]
```diff
@@ -38,7 +38,7 @@ class ShorebirdFlutter {
     final version = await getVersionString(revision: revision);
 
     final installProgress =
-        logger.progress('Installing Flutter revision $version ($revision)');
+        logger.progress('Installing Flutter $version ($revision)');
```
Comment (felangel) [inline packages/shorebird_cli/lib/src/shorebird_flutter.dart]: minor but maybe we can truncate the revision to just the first 10 characters?

Comment (bryanoltman) [reply packages/shorebird_cli/lib/src/shorebird_flutter.dart]: Done
