### PR TITLE
fix(shorebird_cli): support `--split-debug-info`

### LINKED ISSUE #2480: fix: shorebird patch iOS `Failed to link AOT files: Exception: Failed to link:`
**Description**

After successfully creating an iOS release I am unable to create a patch. I get the following error message:
`Failed to link AOT files: Exception: Failed to link:`

**Steps To Reproduce**

1. Create an iOS release
```
shorebird release ios \
    --flavor dev \
    --export-options-plist $EXPORT_OPTIONS_PLIST_PATH \
    -- --split-debug-info=$DEBUG_SYMBOLS_IOS_PATH
```
2. Apply a patch
```
shorebird patch ios \
    --flavor dev --verbose \
    --export-options-plist $EXPORT_OPTIONS_PLIST_PATH \
    -- --split-debug-info=$DEBUG_SYMBOLS_IOS_PATH
```

**Expected Behavior**

The patch is successfully uploaded.

**Screenshots**
Screenshot 2024-09-10 at 3 34 15 PM

**Additional Context**
- Using flutter version `3.24.2`
- Would be happy to jump in a Discord call to run through our process / show the shorebird log file if that would assist, thanks :)

### PR DESCRIPTION
**Pull request by felangel**
## Description

- fix(shorebird_cli): support `--split-debug-info` (closes #2480)
  - when passing the `--split-debug-info` flag to the `flutter_tool`, the resulting `gen_snapshot` execution includes additional flags ('--dwarf-stack-traces', '--resolve-dwarf-paths', '--save-debugging-info') previously, we were proxying this flag when building the release but when building the optimized aot snapshot (as part of the linking step) we were not supplying the additional flags which would result in different vm sections of the generated snapshot.

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [X] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore
- [ ] 🧪 Tests

### CODE REVIEW

**Comment by bryanoltman** [comment]
Would you mind updating the description to explain what is changing?

File: packages/shorebird_cli/lib/src/commands/patch/ios_framework_patcher.dart [hunk 1]
```diff
@@ -51,6 +52,30 @@ class IosFrameworkPatcher extends Patcher {
   @override
   double? get linkPercentage => lastBuildLinkPercentage;
 
+  /// The value of --split-debug-info-path if specified.
+  String? get splitDebugInfoPath =>
+      argResults[CommonArguments.splitDebugInfoArg.name] as String?;
+
+  // TODO(felangel): make this dynamic based on the platform and arch.
+  /// The name of the split debug info file.
+  static const splitDebugInfoFileName = 'app.ios-arm64.symbols';
```
Comment (eseidel) [inline packages/shorebird_cli/lib/src/commands/patch/ios_framework_patcher.dart]: Do we need to throw if we ever try to use this method on the wrong platform?

File: packages/shorebird_cli/lib/src/commands/patch/ios_framework_patcher.dart [hunk 2]
```diff
@@ -51,6 +52,30 @@ class IosFrameworkPatcher extends Patcher {
...
+
+  /// The additional gen_snapshot arguments to use when building the patch with
+  /// `--split-debug-info`.
+  List<String> get splitDebugInfoArgs {
+    return splitDebugInfoPath != null
+        ? [
+            '--dwarf-stack-traces',
+            '--resolve-dwarf-paths',
+            '''--save-debugging-info=${saveDebuggingInfoPath(splitDebugInfoPath!)}''',
```
Comment (eseidel) [inline packages/shorebird_cli/lib/src/commands/patch/ios_framework_patcher.dart]: Did you mean '''

File: packages/shorebird_cli/lib/src/commands/patch/ios_patcher.dart [hunk 3]
```diff
@@ -52,6 +52,30 @@ class IosPatcher extends Patcher {
 
   String get _appDillCopyPath => p.join(buildDirectory.path, 'app.dill');
 
+  /// The value of --split-debug-info-path if specified.
+  String? get splitDebugInfoPath =>
+      argResults[CommonArguments.splitDebugInfoArg.name] as String?;
+
+  // TODO(felangel): make this dynamic based on the platform and arch.
+  /// The name of the split debug info file.
+  static const splitDebugInfoFileName = 'app.ios-arm64.symbols';
```
Comment (eseidel) [inline packages/shorebird_cli/lib/src/commands/patch/ios_patcher.dart:57]: This is duplicated with the releaser?

**Review by eseidel — APPROVED** [review]

File: packages/shorebird_cli/lib/src/commands/patch/ios_framework_patcher.dart (hunk 2 above)
Comment (felangel) [reply packages/shorebird_cli/lib/src/commands/patch/ios_framework_patcher.dart]: Nope, I used the ''' explicitly to maintain the formatting

File: packages/shorebird_cli/lib/src/commands/patch/ios_patcher.dart (hunk 3 above)
Comment (felangel) [reply packages/shorebird_cli/lib/src/commands/patch/ios_patcher.dart:57]: It's duplicated between ios_patcher and ios_framework_patcher but we can refactor in a future PR if we want to share more of the logic.

**Comment by felangel** [comment]
> Would you mind updating the description to explain what is changing?

Yup sorry about that, done 👍

File: packages/shorebird_cli/lib/src/commands/patch/ios_framework_patcher.dart (hunk 1 above)
Comment (felangel) [reply packages/shorebird_cli/lib/src/commands/patch/ios_framework_patcher.dart]: I believe it works as is on other platforms and this additional logic is only needed when we use the linker (only when patching ios and ios_framework)

Comment (felangel) [reply packages/shorebird_cli/lib/src/commands/patch/ios_framework_patcher.dart]: added e2e tests

File: packages/shorebird_cli/lib/src/commands/patch/ios_framework_patcher.dart [hunk 4]
```diff
@@ -108,13 +133,17 @@ class IosFrameworkPatcher extends Patcher {
...
+        Directory(splitDebugInfoPath!).createSync(recursive: true);
+      }
       await artifactBuilder.buildElfAotSnapshot(
         appDillPath: buildResult.kernelFile.path,
         outFilePath: p.join(
           shorebirdEnv.getShorebirdProjectRoot()!.path,
           'build',
           'out.aot',
         ),
+        additionalArgs: [...splitDebugInfoArgs],
```
Comment (bryanoltman) [inline packages/shorebird_cli/lib/src/commands/patch/ios_framework_patcher.dart]:
```suggestion
        additionalArgs: splitDebugInfoArgs,
```

File: packages/shorebird_cli/lib/src/commands/patch/ios_framework_patcher.dart [hunk 5]
```diff
@@ -271,6 +300,7 @@ class IosFrameworkPatcher extends Patcher {
         kernel: _appDillCopyPath,
         outputPath: _vmcodeOutputPath,
         workingDirectory: buildDirectory.path,
+        additionalArgs: [...splitDebugInfoArgs],
```
Comment (bryanoltman) [inline packages/shorebird_cli/lib/src/commands/patch/ios_framework_patcher.dart]:
```suggestion
        additionalArgs: splitDebugInfoArgs,
```

File: packages/shorebird_cli/lib/src/commands/patch/ios_patcher.dart [hunk 6]
```diff
@@ -186,9 +210,13 @@ For more information see: ${supportedFlutterVersionsUrl.toLink()}''',
       }
 
       try {
+        if (splitDebugInfoPath != null) {
+          Directory(splitDebugInfoPath!).createSync(recursive: true);
+        }
         await artifactBuilder.buildElfAotSnapshot(
           appDillPath: ipaBuildResult.kernelFile.path,
           outFilePath: _aotOutputPath,
+          additionalArgs: [...splitDebugInfoArgs],
```
Comment (bryanoltman) [inline packages/shorebird_cli/lib/src/commands/patch/ios_patcher.dart]:
```suggestion
          additionalArgs: splitDebugInfoArgs,
```

File: packages/shorebird_cli/lib/src/commands/patch/ios_patcher.dart [hunk 7]
```diff
@@ -398,6 +426,7 @@ For more information see: ${supportedFlutterVersionsUrl.toLink()}''',
         workingDirectory: buildDirectory.path,
         kernel: kernelFile.path,
         dumpDebugInfoPath: dumpDebugInfoDir?.path,
+        additionalArgs: [...splitDebugInfoArgs],
```
Comment (bryanoltman) [inline packages/shorebird_cli/lib/src/commands/patch/ios_patcher.dart]:
```suggestion
        additionalArgs: splitDebugInfoArgs,
```

File: packages/shorebird_cli/lib/src/common_arguments.dart [hunk 8]
```diff
@@ -99,6 +99,18 @@ The path for a public key .pem file that will be used to validate patch signatur
...
+
+  /// An argument that allows the user to specify a file where program symbols
+  /// are stored.
+  static const splitDebugInfoArg = ArgumentDescriber(
+    name: 'split-debug-info',
+    description: '''
+In a release build, this flag reduces application size by storing Dart program symbols in a separate file on the host rather than
+                                                             in the application. The value of the flag should be a directory where program symbol files can be stored for later use. These
+                                                             symbol files contain the information needed to symbolize Dart stack traces. For an app built with this flag, the "flutter
+                                                             symbolize" command with the right program symbol file is required to obtain a human readable stack trace.
```
Comment (bryanoltman) [inline packages/shorebird_cli/lib/src/common_arguments.dart]: Is there a significance to this level of indentation/line width?

Comment (bryanoltman) [reply packages/shorebird_cli/lib/src/common_arguments.dart]: It renders very oddly in `shorebird release ios-framework -h`
Screenshot 2024-10-23 at 3 09 07 PM

File: packages/shorebird_cli/lib/src/commands/patch/ios_framework_patcher.dart (hunk 4 above)
Comment (felangel) [reply packages/shorebird_cli/lib/src/commands/patch/ios_framework_patcher.dart]: I intentionally did this so that it was easier to add more args in the future but happy to adjust

File: packages/shorebird_cli/lib/src/common_arguments.dart (hunk 8 above)
Comment (felangel) [reply packages/shorebird_cli/lib/src/common_arguments.dart]: ah good call that was just a pasting issue
