### PR TITLE
fix: choose newest xcarchive in ios release

### LINKED ISSUE #2575: fix: shorebird taking build info from the wrong xcarchive for iOS release
App ID: bbbc22d3-7147-4c9e-85e9-ae138aed281d

The Shorebird CLI is pulling build information from the wrong .xcarchive file when `${PRODUCT_NAME}` is set, and different `.xcarchive` files are generated based on the build scheme in Xcode. This causes commands like `shorebird release ios --flavor staging --build-name=1.1.3 --build-number=2` to display the incorrect build name and build number when Shorebird attempts to upload the data to the Shorebird Console. The issue occurs because the Shorebird CLI uses the `production.xcarchive` build information instead of the `staging.xcarchive` build that was just built with the command.

**Steps To Reproduce**

1. Set the ${PRODUCT_NAME} in the Xcode settings for a `staging` scheme.
2. Run shorebird release with the production flavor and specify `--build-name=1.0.0 --build-number=1`.
3. Run shorebird release with the staging flavor and specify `--build-name=1.0.1 --build-number=1`.
4. Shorebird will display a confirmation of the build name and build number before proceeding with the upload to the Shorebird Console.
5. The displayed build name and build number do not match what was specified for the staging build. Instead, the production.xcarchive is used, resulting in 1.0.0+1.

**Expected Behavior**

The build name and build number should match the values specified in the arguments for the `staging` build.

**Screenshots**
The screenshots here doesn't use the versions mentioned in the steps.

1. The build was generated with the specified `build-name` and `build-number`, but the wrong release version was shown and uploaded.
image
<br/><br/>
2. The `production.xcarchive` here contains the release version used by the Shorebird CLI, but this was not built using the command shown above.<br/><br/>
image
<br/><br/>
3. The `staging.xcarchive` here contains the correct release version. The `--verbose` flag confirms that the Flutter build command is executed correctly, but when Shorebird uploads the artifact, it uses the `production.xcarchive` version.<br/><br/>
image

**Additional Context**

None

### PR DESCRIPTION
**Pull request by bryanoltman**
## Description

Updates the ArtifactManager's `getXcarchive` function to return the most recently edited xcarchive rather than the first that appears in `Directory.listSync`

Fixes https://github.com/shorebirdtech/shorebird/issues/2575 and https://github.com/shorebirdtech/shorebird/issues/2549

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore
- [ ] 🧪 Tests

### CODE REVIEW

File: packages/shorebird_cli/lib/src/artifact_manager.dart [hunk 1]
```diff
@@ -282,6 +282,11 @@ class ArtifactManager {
     return archiveDirectory
         .listSync()
         .whereType<Directory>()
+        // Get the most recently modified xcarchive to handle cases where an app
+        // may produce multiple xcarchives with different names.
```
Comment (eseidel) [inline packages/shorebird_cli/lib/src/artifact_manager.dart:286]:
```suggestion
        // may produce multiple xcarchives with different names.
        // This still could grab the wrong ipa, if multiple `flutter` commands
        // are running in parallel or the clock is/was broken on the machine.
        // If either of those occurs in the wild we can check the contents of the
        // xcarchives, but this should be good enough for now.
```

**Review by eseidel — APPROVED** [review]

**Review by felangel — APPROVED** [review]

File: packages/shorebird_cli/lib/src/artifact_manager.dart [hunk 2]
```diff
@@ -282,6 +282,15 @@ class ArtifactManager {
...
+        // This still could grab the wrong ipa, if multiple `flutter` commands
+        // are running in parallel or the clock is/was broken on the machine.
+        // If either of those occurs in the wild we can check the contents of
+        // the xcarchives, but this should be good enough for now.
```
Comment (AhmedLSayed9) [inline packages/shorebird_cli/lib/src/artifact_manager.dart:290]: @bryanoltman 
Isn't this crucial?
As the bug in the `shorebird release` itself, this will break patching too not just previewing. Developer will get a confirmation of the patch successfully published but it'll never be installed for app users.

Comment (bryanoltman) [reply packages/shorebird_cli/lib/src/artifact_manager.dart:290]: It is indeed crucial. We believe that it is a "good enough" fix, in that it will solve the problem in 99.9% of cases, except those outlined in the comment above.

Comment (AhmedLSayed9) [reply packages/shorebird_cli/lib/src/artifact_manager.dart:290]: Understood. Thanks!
