### PR TITLE
fix(shorebird_cli): ignore extension schemes with identifying iOS flavors

### LINKED ISSUE #1703: fix: shorebird init creates an app flavor for an IOS Notification Service Extension
App ID: e789c84d-c5a1-4538-8d5d-21b4d9cfb444

**Description**

Our Flutter project is configured to support FCM images on notification body. Firebase instructs here to create a Notification Service Extension
https://firebase.flutter.dev/docs/messaging/apple-integration#step-1---add-a-notification-service-extension

calling shorebird init creates a flavor for the Notification Service Extension on shorebird.yaml and on shorebird console
**Steps To Reproduce**

So on a flutter ios project supporting Notification Images from FCM

1. setup a Notification Service Extension for the ios project
2. call `shorebird init`
3. shorebird.yaml has a flavor for the Notification Service Extension
4. visit shorebird console on the web
5. see a second app for the Notification Service Extension

**Expected Behavior**

shorebird init should register only a signle app(no flavors)

**Screenshots**

image
image

**Additional Context**

### PR DESCRIPTION
**Pull request by bryanoltman**
## Description

When detecting iOS flavors, ignore schemes that were created for app extensions.

This also removes the now-unused `xcodebuild.list` method.

Fixes https://github.com/shorebirdtech/shorebird/issues/1703

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore
- [ ] 🧪 Tests

### CODE REVIEW

File: packages/shorebird_cli/lib/src/commands/init_command.dart [hunk 1]
```diff
@@ -71,7 +69,7 @@ Please make sure you are running "shorebird init" from within your Flutter proje
     try {
       final flavors = await Future.wait([
         _maybeGetAndroidFlavors(projectRoot.path),
-        _maybeGetiOSFlavors(projectRoot.path),
+        Future.value(ios.flavors()),
```
Comment (erickzanardo) [inline packages/shorebird_cli/lib/src/commands/init_command.dart]: I wonder if we shouldn't make ios.flavors use `async` methods instead of the `sync` ones.

I am not completely sure, but I believe that even though we are calling this wrapped in a `Future.value`, and in a `Future.wait`, it will bloc the execution and not execute android and iOS in parallel.

Either way idk if that is much of an issue anyway, but wanted to raise the wondering.

**Review by erickzanardo — APPROVED** [review]
One wondering, but it LGTM either way.

**Review by felangel — APPROVED** [review]

File: packages/shorebird_cli/lib/src/commands/init_command.dart (hunk 1 above)
Comment (bryanoltman) [reply packages/shorebird_cli/lib/src/commands/init_command.dart]: I cleaned this up a bit to remove the `Future.wait` and have it just be:

```dart
      androidFlavors = await _maybeGetAndroidFlavors(projectRoot.path);
      iosFlavors = ios.flavors();
```
