### PR TITLE
fix(shorebird_cli): exit with non-zero code if unpatchable changes are detected on CI

### LINKED ISSUE #1145: fix: unpatchable warnings exit with code 0 on CI
This should use a non-zero exit code (and probably print "Exiting..." or something similar).

### PR DESCRIPTION
**Pull request by bryanoltman**
## Description

If an unpatchable change is detected in a non-interactive environment (i.e., CI), throw an exception and exit with code 70.

Fixes https://github.com/shorebirdtech/shorebird/issues/1145

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

File: packages/shorebird_cli/lib/src/commands/patch/patch_aar_command.dart [hunk 1]
```diff
@@ -206,18 +206,24 @@ Please re-run the release command for this version or create a new release.''');
...
-      ),
-      releaseArtifactUrl: Uri.parse(releaseAarArtifact.url),
-      archiveDiffer: _archiveDiffer,
-      force: force,
-    );
+        releaseArtifactUrl: Uri.parse(releaseAarArtifact.url),
+        archiveDiffer: _archiveDiffer,
+        force: force,
+      );
+    } on UnpatchableChangeException {
```
Comment (eseidel) [inline packages/shorebird_cli/lib/src/commands/patch/patch_aar_command.dart:223]: I'm trying to think how I would do this in Rust.

I suspect what you may end up wanting is for both the normal exit and the failed exit to both be handled via exception and whatever caller to this be able to handle such an exception.

Then callers just look like this:

```
await patchDiffChecker.confirmUnpatchableDiffsIfNecessary();
```

And some outer layer knows about:

try {
command()
} on ExitException catch (e) {
  return e.exitCode;
}

Or similar?

Comment (bryanoltman) [reply packages/shorebird_cli/lib/src/commands/patch/patch_aar_command.dart:223]: I like that. Just pushed a commit to standardize the control flow.

**Review by eseidel — APPROVED** [review]
