### PR TITLE
fix(shorebird_cli): cache artifact download error handling

### LINKED ISSUE #1006: fix: invalid or corrupt bundletool
When creating a release, a couple users have reported an error of the form `Failed to extract version code from app bundle: Error: Invalid or corrupt jarfile /path/to/bundletool.jar`

### PR DESCRIPTION
**Pull request by felangel**
## Description

- fix(shorebird_cli): cache artifact download error handling (closes #1006)

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [X] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

File: packages/shorebird_cli/lib/src/cache.dart [hunk 1]
```diff
@@ -11,6 +11,15 @@ import 'package:shorebird_cli/src/platform.dart';
 import 'package:shorebird_cli/src/process.dart';
 import 'package:shorebird_cli/src/shorebird_env.dart';
 
+class CacheUpdateFailure implements Exception {
```
Comment (bryanoltman) [inline packages/shorebird_cli/lib/src/cache.dart:19]: Doc comments here

File: packages/shorebird_cli/lib/src/cache.dart [hunk 2]
```diff
@@ -128,7 +137,23 @@ abstract class CachedArtifact {
...
-    final response = await cache.httpClient.send(request);
+    final http.StreamedResponse response;
+    try {
+      response = await cache.httpClient.send(request);
+    } catch (error) {
+      throw CacheUpdateFailure(
+        '''
+Failed to download $name: $error
+If you're behind a firewall/proxy, please, make sure shorebird_cli is
+allowed to access $storageUrl.''',
```
Comment (bryanoltman) [inline packages/shorebird_cli/lib/src/cache.dart:155]: Love it

**Review by bryanoltman — APPROVED** [review]

File: packages/shorebird_cli/lib/src/cache.dart (hunk 1 above)
Comment (felangel) [reply packages/shorebird_cli/lib/src/cache.dart:19]: Oops good call will update 👍
