### PR TITLE
fix(shorebird_cli): don't fail if a release artifact has already been uploaded

### LINKED ISSUE #553: chore(shorebird_code_push_client): add detail to error messages when requests fail
**Description**

We often just throw an exception containing the error test or "an unknown error occurred" instead of providing context about things like which call failed, etc.

There may also be associated work to improve this messaging on the backend.

### PR DESCRIPTION
**Pull request by bryanoltman**
## Description

`shorebird release` currently fails if it detects that an artifact already exists for a given architecture. This can cause problems if a user's connection is unstable and only some artifact uploads succeed, leaving them in a state where they are unable to complete their release.

This change updates the release artifact upload logic to log when 409s (HttpStatus.conflict) are received instead of aborting the release.

Fixes https://github.com/shorebirdtech/shorebird/issues/553

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

File: packages/shorebird_code_push_client/lib/src/code_push_client.dart [hunk 1]
```diff
@@ -139,7 +147,13 @@ class CodePushClient {
     final response = await _httpClient.send(request);
     final body = await response.stream.bytesToString();
 
-    if (response.statusCode != HttpStatus.ok) throw _parseErrorResponse(body);
+    if (response.statusCode == HttpStatus.conflict) {
+      throw ResourceConflictException(
```
Comment (felangel) [inline packages/shorebird_code_push_client/lib/src/code_push_client.dart]: Thoughts on not overwriting the message from the server? We're duplicating the same message in multiple places and the CLI isn't using the message for anything at the moment so it seems unnecessary.

Comment (felangel) [inline packages/shorebird_code_push_client/lib/src/code_push_client.dart]: Thoughts on adjusting to:

```dart
class CodePushConflict extends CodePushException {
  CodePushConflict({super.message, super.details});
}
```

And adjusting `_parseErrorResponse` to handle conflicts in a generic way?

Comment (felangel) [reply packages/shorebird_code_push_client/lib/src/code_push_client.dart]: See https://github.com/shorebirdtech/shorebird/pull/561

**Review by felangel — APPROVED** [review]
