### PR TITLE
fix(shorebird_cli): properly determine android studio path on Windows

### LINKED ISSUE #1578: fix: "Android Studio 2022" installation folder is not detected
At `android_studio.dart:32`, the code does not look for installation location that look like "Android Studio 2022". It should look for a range of years, like 2010-2050, probably.

Edit : How Flutter searches for it : https://github.com/flutter/flutter/blob/32d42b63def2ea2ab358ff554c959aa02ac4e8ec/packages/flutter_tools/lib/src/android/android_studio.dart#L362

### PR DESCRIPTION
**Pull request by bryanoltman**
## Description

Following the example of the `flutter` tool, look in the user's LocalAppData directory for an Android Studio folder that points to a valid install.

Fixes https://github.com/shorebirdtech/shorebird/issues/1578

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

File: packages/shorebird_cli/lib/src/android_studio.dart [hunk 1]
```diff
@@ -15,41 +18,92 @@ AndroidStudio get androidStudio => read(androidStudioRef);
...
+    if (!localAppData.isNullOrEmpty) {
+      final cacheDir = Directory(p.join(localAppData!, 'Google'));
+      if (cacheDir.existsSync()) {
+        // This directory should contain, among other things,
+        // AndroidStudioYYYY.N entries, where YYYY is the year and N is the
+        // version number. Within these directories, there should be a .home
+        // file that contains the path to the Android Studio installation. We
+        // want to find the directory with the highest version number that
+        // points to a valid installation and return that.
+        final studioRegex = RegExp(r'AndroidStudio(\d+\.\d+)');
```
Comment (felangel) [inline packages/shorebird_cli/lib/src/android_studio.dart]:
```suggestion
        final androidStudioRegex = RegExp(r'AndroidStudio(\d+\.\d+)');
```
nit

File: packages/shorebird_cli/test/src/android_studio_test.dart [hunk 2]
```diff
@@ -36,57 +36,130 @@ void main() {
...
-        )..createSync(recursive: true);
-        when(() => platform.isWindows).thenReturn(false);
-        when(() => platform.isMacOS).thenReturn(true);
-        when(() => platform.isLinux).thenReturn(false);
-        when(() => platform.environment).thenReturn({'HOME': tempDir.path});
-        await expectLater(
-          runWithOverrides(() => androidStudio.path),
-          equals(androidStudioDir.path),
-        );
+      group('on MacOS', () {
```
Comment (felangel) [inline packages/shorebird_cli/test/src/android_studio_test.dart:120]: Love the test reorg 💯

**Review by felangel — APPROVED** [review]

File: packages/shorebird_cli/lib/src/android_studio.dart (hunk 1 above)
Comment (bryanoltman) [reply packages/shorebird_cli/lib/src/android_studio.dart]: Fixed
