### PR TITLE
fix(shorebird_cli): don't check for ipa when generating an unsigned release

### LINKED ISSUE #1335: `shorebird release ios-alpha --no-codesign` fails to find ipa
This command does not generate an ipa and will consequently fail to find one. I believe this had only succeeded for me locally because I had previously built without the `--no-codesign` flag and had an ipa hanging around in my build folder.

### PR DESCRIPTION
**Pull request by bryanoltman**
## Description

We don't generate an ipa if codesigning is disabled, so only attempt to find an ipa path in that case.

Fixes https://github.com/shorebirdtech/shorebird/issues/1335

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

File: packages/shorebird_cli/test/src/commands/release/release_ios_command_test.dart [hunk 1]
```diff
@@ -635,9 +635,7 @@ error: exportArchive: No signing certificate "iOS Distribution" found
       );
 
       expect(exitCode, equals(ExitCode.software.code));
-      verify(
-        () => logger.err(any(that: contains('No directory found'))),
```
Comment (felangel) [inline packages/shorebird_cli/test/src/commands/release/release_ios_command_test.dart:639]: Where was this No directory found previously coming from?

Comment (felangel) [reply packages/shorebird_cli/test/src/commands/release/release_ios_command_test.dart:639]: Ah nvm it was from the remaining error when an ipa file was not found.

**Review by felangel — APPROVED** [review]

File: packages/shorebird_cli/test/src/commands/release/release_ios_command_test.dart (hunk 1 above)
Comment (bryanoltman) [reply packages/shorebird_cli/test/src/commands/release/release_ios_command_test.dart:639]: https://github.com/shorebirdtech/shorebird/blob/bo/unsigned-ipa/packages/shorebird_cli/lib/src/shorebird_artifact_mixin.dart#L127
