### PR TITLE
fix(shorebird_cli): support `shorebird preview` for iOS 17+ devices

### LINKED ISSUE #1292: fix: `shorebird preview` fails with Xcode 15/iOS 17
**Description**

When running `shorebird preview` on a machine with Xcode 15 targeting an iPhone running iOS 17, the deployment to the device fails with the following message:

```
⠇ [ 95%] GeneratingApplicationMap... (6.6s)2023-09-19 17:33:40.706 ios-deploy[5779:22498] [ !! ] Unable to locate DeviceSupport directory with suffix 'DeveloperDiskImage.dmg'. This probably means you don't have Xcode installed, you will need to launch the app manually and logging output will not be shown!
```

### PR DESCRIPTION
**Pull request by bryanoltman**
## Description

Uses the `devicectl` utility to allow `shorebird preview` to launch iOS apps on devices running iOS 17 or higher.

Fixes https://github.com/shorebirdtech/shorebird/issues/1292

Note: this fails in the same way as before if one attempts to run `shorebird preview` with:

- device running iOS 17+
- Xcode <15

However, as one cannot deploy to an iOS 17+ device without Xcode >=15, and one cannot run Xcode <15 on the latest version of macOS, I don't believe this is worth our time to fix.

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

File: packages/shorebird_cli/lib/src/executables/devicectl/devicectl.dart [hunk 1]
```diff
@@ -0,0 +1,311 @@
...
+      return devices.firstWhereOrNull((d) => d.identifier == deviceId);
+    } else {
+      return devices.firstOrNull;
+    }
+  }
+
+  /// Whether we should use `devicectl` to install and launch the app on the
+  /// device with the given [deviceId], or the first available device we find if
+  /// [deviceId] is not provided.
+  Future<bool> shouldUseDevicectl({String? deviceId}) async {
```
Comment (felangel) [inline packages/shorebird_cli/lib/src/executables/devicectl/devicectl.dart]:
```suggestion
  Future<bool> isSupported({String? deviceId}) async {
```

nit but I feel this would read a bit better

File: packages/shorebird_cli/lib/src/commands/preview_command.dart [hunk 2]
```diff
@@ -320,13 +320,30 @@ class PreviewCommand extends ShorebirdCommand {
...
     try {
-      final exitCode = await iosDeploy.installAndLaunchApp(
-        bundlePath: runnerDirectory.path,
+      final shouldUseDeviceCtl = await devicectl.shouldUseDevicectl(
         deviceId: deviceId,
       );
+
+      final int exitCode;
+      if (shouldUseDeviceCtl) {
+        logger.detail('Using devicectl for install and launch.');
```
Comment (felangel) [inline packages/shorebird_cli/lib/src/commands/preview_command.dart]:
```suggestion
        logger.detail('Using devicectl to install and launch.');
```

nit

File: packages/shorebird_cli/lib/src/commands/preview_command.dart [hunk 3]
```diff
@@ -320,13 +320,30 @@ class PreviewCommand extends ShorebirdCommand {
...
+        exitCode = await devicectl.installAndLaunchApp(
+          runnerAppDirectory: runnerDirectory,
+          deviceId: deviceId,
+        );
+      } else {
+        logger.detail('Using ios-deploy for install and launch.');
```
Comment (felangel) [inline packages/shorebird_cli/lib/src/commands/preview_command.dart]:
```suggestion
        logger.detail('Using ios-deploy to install and launch.');
```

File: packages/shorebird_cli/lib/src/executables/devicectl/apple_device.dart [hunk 4]
```diff
@@ -0,0 +1,99 @@
+import 'package:json_annotation/json_annotation.dart';
+import 'package:pub_semver/pub_semver.dart';
+import 'package:shorebird_cli/src/extensions/version.dart';
+
+part 'apple_device.g.dart';
+
+/// {@template apple_device}
+/// A pared-down version of a CoreDevice, as represented in the JSON output of
+/// `xcrun devicectl list devices`.
```
Comment (felangel) [inline packages/shorebird_cli/lib/src/executables/devicectl/apple_device.dart:10]: I assume there's no link to a schema/docs we could link to? 🤣

File: packages/shorebird_cli/lib/src/executables/devicectl/apple_device.dart [hunk 5]
```diff
@@ -0,0 +1,99 @@
...
+/// {@endtemplate}
+@JsonSerializable(createToJson: false, fieldRename: FieldRename.none)
+
+/// {@macro apple_device}
+class AppleDevice {
+  AppleDevice({
```
Comment (felangel) [inline packages/shorebird_cli/lib/src/executables/devicectl/apple_device.dart]:
```suggestion
  const AppleDevice({
```

File: packages/shorebird_cli/lib/src/executables/devicectl/apple_device.dart [hunk 6]
```diff
@@ -0,0 +1,99 @@
...
+
+  /// Whether the device is available for use. See the docs for
+  /// [ConnectionProperties.tunnelState] for more information about known
+  /// tunnelState values and what they (seem to) represent.
+  bool get isAavailable => connectionProperties.tunnelState != 'unavailable';
+}
+
+@JsonSerializable(createToJson: false, fieldRename: FieldRename.none)
+class HardwareProperties {
+  HardwareProperties({required this.platform});
```
Comment (felangel) [inline packages/shorebird_cli/lib/src/executables/devicectl/apple_device.dart]:
```suggestion
  const HardwareProperties({required this.platform});
```

File: packages/shorebird_cli/lib/src/executables/devicectl/apple_device.dart [hunk 7]
```diff
@@ -0,0 +1,99 @@
...
+  /// The device's platform (e.g., "iOS").
+  final String platform;
+
+  static HardwareProperties fromJson(Map<String, dynamic> json) =>
+      _$HardwarePropertiesFromJson(json);
+}
+
+@JsonSerializable(createToJson: false, fieldRename: FieldRename.none)
+class DeviceProperties {
+  DeviceProperties({required this.name, this.osVersionNumber});
```
Comment (felangel) [inline packages/shorebird_cli/lib/src/executables/devicectl/apple_device.dart]:
```suggestion
  const DeviceProperties({required this.name, this.osVersionNumber});
```

File: packages/shorebird_cli/lib/src/executables/devicectl/apple_device.dart [hunk 8]
```diff
@@ -0,0 +1,99 @@
...
+  /// The device's OS version as a string (e.g., "14.4.1").
+  final String? osVersionNumber;
+
+  static DeviceProperties fromJson(Map<String, dynamic> json) =>
+      _$DevicePropertiesFromJson(json);
+}
+
+@JsonSerializable(createToJson: false, fieldRename: FieldRename.none)
+class ConnectionProperties {
+  ConnectionProperties({required this.tunnelState});
```
Comment (felangel) [inline packages/shorebird_cli/lib/src/executables/devicectl/apple_device.dart]:
```suggestion
  const ConnectionProperties({required this.tunnelState});
```

File: packages/shorebird_cli/lib/src/executables/devicectl/apple_device.dart [hunk 9]
```diff
@@ -0,0 +1,99 @@
...
+    required this.hardwareProperties,
+    required this.connectionProperties,
+  });
+
+  /// Creates an [AppleDevice] from JSON.
+  static AppleDevice fromJson(Map<String, dynamic> json) =>
+      _$AppleDeviceFromJson(json);
+
+  /// The device's unique identifier of the form
+  /// DEADBEEF-DEAD-BEEF-DEAD-BEEFDEADBEEF.
```
Comment (felangel) [inline packages/shorebird_cli/lib/src/executables/devicectl/apple_device.dart:27]: 🤣

File: packages/shorebird_cli/lib/src/executables/devicectl/apple_device.dart [hunk 10]
```diff
@@ -0,0 +1,99 @@
...
+  /// The device's OS version as a [Version], or `null` if the version string
+  /// cannot be parsed.
+  Version? get osVersion => osVersionString == null
+      ? null
+      : VersionParsing.tryParse(osVersionString!);
+
+  /// Whether the device is available for use. See the docs for
+  /// [ConnectionProperties.tunnelState] for more information about known
+  /// tunnelState values and what they (seem to) represent.
+  bool get isAavailable => connectionProperties.tunnelState != 'unavailable';
```
Comment (felangel) [inline packages/shorebird_cli/lib/src/executables/devicectl/apple_device.dart]:
```suggestion
  bool get isAvailable => connectionProperties.tunnelState != 'unavailable';
```

File: packages/shorebird_cli/lib/src/executables/devicectl/devicectl.dart (hunk 1 above)
Comment (felangel) [reply packages/shorebird_cli/lib/src/executables/devicectl/devicectl.dart]: or maybe `isCoreDevice`?

File: packages/shorebird_cli/lib/src/executables/devicectl/devicectl.dart [hunk 11]
```diff
@@ -0,0 +1,311 @@
...
+      'install',
+      'app',
+      '--device',
+      deviceId,
+      runnerApp.path,
+    ];
+    final Json jsonResult;
+    try {
+      jsonResult = await _runJsonCommand(args: args);
+    } catch (error) {
```
Comment (felangel) [inline packages/shorebird_cli/lib/src/executables/devicectl/devicectl.dart:112]:
```suggestion
    } on Exception catch (error) {
```

so we don't need to cast below

File: packages/shorebird_cli/lib/src/executables/devicectl/devicectl.dart [hunk 12]
```diff
@@ -0,0 +1,311 @@
...
+      throw DevicectlException(
+        message: failureErrorMessage,
+        underlyingException: error as Exception,
+      );
+    }
+
+    final String bundleId;
+    try {
+      final maybeBundleId =
+          JsonPath(r'$.result.installedApplications[0].bundleID')
```
Comment (felangel) [inline packages/shorebird_cli/lib/src/executables/devicectl/devicectl.dart:122]: fancy ✨

File: packages/shorebird_cli/lib/src/executables/devicectl/devicectl.dart [hunk 13]
```diff
@@ -0,0 +1,311 @@
...
+              .firstOrNull
+              ?.value as String?;
+      if (maybeBundleId == null) {
+        throw Exception(
+          'Unable to find installed app bundleID in devicectl output',
+        );
+      }
+
+      bundleId = maybeBundleId;
+    } catch (error) {
```
Comment (felangel) [inline packages/shorebird_cli/lib/src/executables/devicectl/devicectl.dart:133]:
```suggestion
    } on Exception catch (error) {
```

File: packages/shorebird_cli/lib/src/executables/devicectl/devicectl.dart [hunk 14]
```diff
@@ -0,0 +1,311 @@
...
+      'process',
+      'launch',
+      '--device',
+      deviceId,
+      bundleId,
+    ];
+
+    try {
+      await _runJsonCommand(args: args);
+    } catch (error) {
```
Comment (felangel) [inline packages/shorebird_cli/lib/src/executables/devicectl/devicectl.dart:164]:
```suggestion
    } on Exception catch (error) {
```

File: packages/shorebird_cli/lib/src/executables/devicectl/devicectl.dart [hunk 15]
```diff
@@ -0,0 +1,311 @@
...
+  DevicectlException({
+    required this.message,
+    this.underlyingException,
+  });
+
+  /// A message describing this exception.
+  final String message;
+
+  /// The exception that caused this exception to be thrown, if any.
+  final Exception? underlyingException;
```
Comment (felangel) [inline packages/shorebird_cli/lib/src/executables/devicectl/devicectl.dart]: Or should this just be an `Object?` to align with `catch`?

File: packages/shorebird_cli/lib/src/executables/devicectl/devicectl.dart (hunk 1 above)
Comment (bryanoltman) [reply packages/shorebird_cli/lib/src/executables/devicectl/devicectl.dart]: Yeah, I went through a few iterations of naming this and didn't land on anything I liked. Will do this.

File: packages/shorebird_cli/lib/src/executables/devicectl/devicectl.dart [hunk 16]
```diff
@@ -0,0 +1,311 @@
...
+  /// Lists iOS devices that we can install and launch apps on.
+  Future<List<AppleDevice>> listAvailableIosDevices() async {
+    const failureErrorMessage = 'Failed to list devices';
+
+    final args = [
+      ...baseArgs,
+      'list',
+      'devices',
+      '--timeout',
+      '5',
```
Comment (felangel) [inline packages/shorebird_cli/lib/src/executables/devicectl/devicectl.dart]: is this 5 seconds?

File: packages/shorebird_cli/lib/src/executables/devicectl/devicectl.dart (hunk 1 above)
Comment (bryanoltman) [reply packages/shorebird_cli/lib/src/executables/devicectl/devicectl.dart]: Done

File: packages/shorebird_cli/lib/src/executables/devicectl/devicectl.dart [hunk 17]
```diff
@@ -0,0 +1,311 @@
...
+
+    final result = await process.run(executableName, [
+      ...args,
+      '--json-output',
+      jsonOutputFile.path,
+    ]);
+
+    // The `devicectl` command will still write json output if it fails, so in
+    // the event of a non-zero exit code, only throw a ProcessException if we
+    //can't find the output file.
```
Comment (felangel) [inline packages/shorebird_cli/lib/src/executables/devicectl/devicectl.dart]:
```suggestion
    // can't find the output file.
```

File: packages/shorebird_cli/lib/src/executables/devicectl/apple_device.dart (hunk 4 above)
Comment (bryanoltman) [reply packages/shorebird_cli/lib/src/executables/devicectl/apple_device.dart:10]: If only. `devicectl` seems to be entirely undocumented. The flutter_tool comments simply reference json output :(

File: packages/shorebird_cli/lib/src/executables/devicectl/apple_device.dart (hunk 10 above)
Comment (bryanoltman) [reply packages/shorebird_cli/lib/src/executables/devicectl/apple_device.dart]: Done

File: packages/shorebird_cli/lib/src/executables/devicectl/nserror.dart [hunk 18]
```diff
@@ -0,0 +1,66 @@
...
+
+/// {@template nserror}
+/// A pared-down representation of the NSError class.
+///
+/// See https://developer.apple.com/documentation/foundation/nserror.
+/// {@endtemplate}
+@JsonSerializable(createToJson: false, fieldRename: FieldRename.none)
+class NSError {
+  /// {@macro nserror}
+  NSError({
```
Comment (felangel) [inline packages/shorebird_cli/lib/src/executables/devicectl/nserror.dart]:
```suggestion
  const NSError({
```

File: packages/shorebird_cli/lib/src/executables/devicectl/apple_device.dart (hunk 8 above)
Comment (bryanoltman) [reply packages/shorebird_cli/lib/src/executables/devicectl/apple_device.dart]: Done

File: packages/shorebird_cli/lib/src/executables/devicectl/apple_device.dart (hunk 7 above)
Comment (bryanoltman) [reply packages/shorebird_cli/lib/src/executables/devicectl/apple_device.dart]: Done

File: packages/shorebird_cli/lib/src/executables/devicectl/apple_device.dart (hunk 6 above)
Comment (bryanoltman) [reply packages/shorebird_cli/lib/src/executables/devicectl/apple_device.dart]: Done

File: packages/shorebird_cli/lib/src/executables/devicectl/nserror.dart [hunk 19]
```diff
@@ -0,0 +1,66 @@
...
+    required this.domain,
+    required this.userInfo,
+  });
+
+  final int code;
+  final String domain;
+  final UserInfo userInfo;
+
+  /// Creates an [NSError] from JSON.
+  static NSError fromJson(Map<String, dynamic> json) => _$NSErrorFromJson(json);
```
Comment (felangel) [inline packages/shorebird_cli/lib/src/executables/devicectl/nserror.dart]:
```suggestion
  static NSError fromJson(Json json) => _$NSErrorFromJson(json);
```

File: packages/shorebird_cli/lib/src/executables/devicectl/apple_device.dart (hunk 5 above)
Comment (bryanoltman) [reply packages/shorebird_cli/lib/src/executables/devicectl/apple_device.dart]: Done

File: packages/shorebird_cli/lib/src/executables/devicectl/nserror.dart [hunk 20]
```diff
@@ -0,0 +1,66 @@
...
+      _$UserInfoFromJson(json);
+}
+
+@JsonSerializable(createToJson: false, fieldRename: FieldRename.none)
+class StringContainer {
+  StringContainer({required this.string});
+
+  final String string;
+
+  static StringContainer fromJson(Map<String, dynamic> json) =>
```
Comment (felangel) [inline packages/shorebird_cli/lib/src/executables/devicectl/nserror.dart]:
```suggestion
  static StringContainer fromJson(Json json) =>
```

File: packages/shorebird_cli/lib/src/executables/devicectl/nserror.dart [hunk 21]
```diff
@@ -0,0 +1,66 @@
...
+      _$StringContainerFromJson(json);
+}
+
+@JsonSerializable(createToJson: false, fieldRename: FieldRename.none)
+class NSUnderlyingError {
+  NSUnderlyingError({required this.error});
+
+  final NSError? error;
+
+  static NSUnderlyingError fromJson(Map<String, dynamic> json) =>
```
Comment (felangel) [inline packages/shorebird_cli/lib/src/executables/devicectl/nserror.dart]:
```suggestion
  static NSUnderlyingError fromJson(Json json) =>
```

File: packages/shorebird_cli/lib/src/executables/devicectl/devicectl.dart (hunk 11 above)
Comment (bryanoltman) [reply packages/shorebird_cli/lib/src/executables/devicectl/devicectl.dart:112]: Done

File: packages/shorebird_cli/lib/src/executables/devicectl/devicectl.dart (hunk 13 above)
Comment (bryanoltman) [reply packages/shorebird_cli/lib/src/executables/devicectl/devicectl.dart:133]: Done

File: packages/shorebird_cli/lib/src/executables/devicectl/devicectl.dart (hunk 14 above)
Comment (bryanoltman) [reply packages/shorebird_cli/lib/src/executables/devicectl/devicectl.dart:164]: Done

**Review by felangel — APPROVED** [review]
Left a few small comments but overall LGTM ✅

File: packages/shorebird_cli/lib/src/executables/devicectl/devicectl.dart (hunk 16 above)
Comment (bryanoltman) [reply packages/shorebird_cli/lib/src/executables/devicectl/devicectl.dart]: Yep. Updated to be:

```dart
const timeout = Duration(seconds: 5);
// ...
'${timeout.inSeconds}',   
```

File: packages/shorebird_cli/lib/src/executables/devicectl/nserror.dart (hunk 18 above)
Comment (bryanoltman) [reply packages/shorebird_cli/lib/src/executables/devicectl/nserror.dart]: Done

File: packages/shorebird_cli/lib/src/executables/devicectl/nserror.dart (hunk 21 above)
Comment (bryanoltman) [reply packages/shorebird_cli/lib/src/executables/devicectl/nserror.dart]: Done

File: packages/shorebird_cli/lib/src/executables/devicectl/nserror.dart (hunk 20 above)
Comment (bryanoltman) [reply packages/shorebird_cli/lib/src/executables/devicectl/nserror.dart]: Done

File: packages/shorebird_cli/lib/src/executables/devicectl/nserror.dart (hunk 19 above)
Comment (bryanoltman) [reply packages/shorebird_cli/lib/src/executables/devicectl/nserror.dart]: Done

File: packages/shorebird_cli/lib/src/executables/devicectl/devicectl.dart (hunk 15 above)
Comment (bryanoltman) [reply packages/shorebird_cli/lib/src/executables/devicectl/devicectl.dart]: Good call, this also lets us avoid the `on Exception`s below. Done

File: packages/shorebird_cli/lib/src/executables/devicectl/devicectl.dart (hunk 12 above)
Comment (bryanoltman) [reply packages/shorebird_cli/lib/src/executables/devicectl/devicectl.dart:122]: Haha I was a bit torn about keeping this in, as we pull in the `json_path` package for this one line. It probably saves us some bug-prone parsing though, so 🤷
