### PR TITLE
fix(shorebird_cli): handle multi-dimensional flavors on android

### LINKED ISSUE #1830: fix: flavors with multiple dimensions cause release command to not find aab
With flavors across multiple dimensions, our release command cannot find the generated aab.

For example:

```gradle
    flavorDimensions "track", "country"
    productFlavors {
        internal {
            dimension "track"
            applicationIdSuffix ".internal"
            manifestPlaceholders = [applicationLabel: "[Internal] Shorebird Example"]
        }
        stable {
            dimension "track"
            manifestPlaceholders = [applicationLabel: "Shorebird Example"]
        }
        global {
            applicationIdSuffix ".gl"
            dimension "country"
            manifestPlaceholders = [applicationLabel: "Shorebird Example"]
        }
        local {
            applicationIdSuffix ".lcl"
            dimension "country"
            manifestPlaceholders = [applicationLabel: "Shorebird Example"]
        }
    }
```

With this, running `shorebird release android --flavor stableGlobal` generates an aab at `build/app/outputs/bundle/stableGlobalRelease/app-stable-global-release.aab`, but our tool fails with:

```
✗ Exception: Failed to extract version name from app bundle: [BT:1.15.6] Error: File '/Users/bryanoltman/shorebirdtech/samples/flavors/build/app/outputs/bundle/stableGlobalRelease/app-stableGlobal-release.aab' was not found.
java.lang.IllegalArgumentException: File '/Users/bryanoltman/shorebirdtech/samples/flavors/build/app/outputs/bundle/stableGlobalRelease/app-stableGlobal-release.aab' was not found.
```

Changing `stable` and `global` to `stableFlavor` and `globalFlavor` yields:

`✗ Failed to build: Gradle build failed to produce an .aab file. It's likely that this file was generated under /Users/bryanoltman/shorebirdtech/samples/flavors/build, but the tool couldn't find it.`

The output:

```
⑆ l /Users/bryanoltman/shorebirdtech/samples/flavors/build/app/outputs/bundle/stableFlavorGlobalFlavorRelease
total 50104
drwxr-xr-x@ 3 bryanoltman  staff    96B Apr 22 12:09 .
drwxr-xr-x@ 7 bryanoltman  staff   224B Apr 22 12:09 ..
-rw-r--r--@ 1 bryanoltman  staff    24M Apr 22 12:09 app-stableFlavor-globalFlavor-release.aab
```

_Originally posted by @AbhijithKonnayil in https://github.com/shorebirdtech/shorebird/issues/515#issuecomment-2022555249_

### PR DESCRIPTION
**Pull request by erickzanardo**
## Description

Our CLI would get confused when using multi dimensional flavors on android. This PR fixes that.

Fixes #1830 

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

File: packages/shorebird_cli/lib/src/commands/release/release_android_command.dart [hunk 1]
```diff
@@ -195,36 +195,31 @@ Use `shorebird flutter versions list` to list available versions.
...
 
-        final bundleDirPath = p.join(
-          projectRoot.path,
-          'build',
-          'app',
-          'outputs',
-          'bundle',
-        );
+        String? bundlePath;
+        String? apkPath;
```
Comment (eseidel) [inline packages/shorebird_cli/lib/src/commands/release/release_android_command.dart]: Do these need to be nullable?

Dart supports fancy:
```
final Foo foo;
try {
   foo = thing();
} catch () {
   logger.info('failed');
   return;
}
```
It will do flow analysis to know that the finals are set during the try or not used after.

Comment (eseidel) [reply packages/shorebird_cli/lib/src/commands/release/release_android_command.dart]: Ah, nevermind. I see they can get explicitly set to null.

File: packages/shorebird_cli/lib/src/shorebird_android_artifacts.dart [hunk 2]
```diff
@@ -0,0 +1,110 @@
+import 'package:path/path.dart' as p;
+import 'package:scoped/scoped.dart';
+import 'package:shorebird_cli/src/command.dart';
+import 'package:shorebird_cli/src/third_party/flutter_tools/lib/flutter_tools.dart';
+
+/// Throw when multiple artifacts are found in the build directory.
```
Comment (eseidel) [inline packages/shorebird_cli/lib/src/shorebird_android_artifacts.dart]: Will that happen when using Android Studio and building different flavors/configs between multiple runs?  I wonder if older .aab's from other configs being in the build dir can cause these failures to happen?

File: packages/shorebird_cli/lib/src/shorebird_android_artifacts.dart [hunk 3]
```diff
@@ -0,0 +1,110 @@
...
+  @override
+  String toString() {
+    return 'Multiple artifacts found in $buildDir: '
+        '${foundArtifacts.map((e) => e.path)}';
+  }
+}
+
+extension on String {
+  String get artifactId => replaceAll(RegExp(r'\W'), '').toLowerCase();
+}
```
Comment (eseidel) [inline packages/shorebird_cli/lib/src/shorebird_android_artifacts.dart:66]: I believe this makes it anonymous and thus local to this file, correct?

File: packages/shorebird_cli/lib/src/shorebird_android_artifacts.dart [hunk 4]
```diff
@@ -0,0 +1,110 @@
...
+
+final shorebirdAndroidArtifactsRef = create(ShorebirdAndroidArtifacts.new);
+
+ShorebirdAndroidArtifacts get shorebirdAndroidArtifacts =>
+    read(shorebirdAndroidArtifactsRef);
```
Comment (eseidel) [inline packages/shorebird_cli/lib/src/shorebird_android_artifacts.dart:71]: @felangel is our style to use globals for things like this?

File: packages/shorebird_cli/lib/src/shorebird_android_artifacts.dart [hunk 5]
```diff
@@ -0,0 +1,110 @@
...
+
+/// Mixin on [ShorebirdCommand] which exposes methods
+// to find the artifacts generated for android
+class ShorebirdAndroidArtifacts {
+  /// Find the artifact in the build directory.
+  String? findArtifact({
+    required String artifactName,
+    required String buildDir,
```
Comment (eseidel) [inline packages/shorebird_cli/lib/src/shorebird_android_artifacts.dart]: Should this be a Directory type?

File: packages/shorebird_cli/lib/src/shorebird_android_artifacts.dart [hunk 6]
```diff
@@ -0,0 +1,110 @@
...
+
+ShorebirdAndroidArtifacts get shorebirdAndroidArtifacts =>
+    read(shorebirdAndroidArtifactsRef);
+
+/// Mixin on [ShorebirdCommand] which exposes methods
+// to find the artifacts generated for android
+class ShorebirdAndroidArtifacts {
+  /// Find the artifact in the build directory.
+  String? findArtifact({
+    required String artifactName,
```
Comment (eseidel) [inline packages/shorebird_cli/lib/src/shorebird_android_artifacts.dart:78]: Should this be an enum or File?

File: packages/shorebird_cli/lib/src/shorebird_android_artifacts.dart [hunk 7]
```diff
@@ -0,0 +1,110 @@
...
+
+    final allFiles = directory.listSync();
+    final candidates = allFiles.where((file) {
+      final fileName = p.basename(file.path);
+      return fileName.artifactId == artifactId;
+    }).toList();
+
+    if (candidates.isEmpty) {
+      return null;
+    } else if (candidates.length > 1) {
```
Comment (eseidel) [inline packages/shorebird_cli/lib/src/shorebird_android_artifacts.dart]: No need for else after return.

File: packages/shorebird_cli/lib/src/shorebird_android_artifacts.dart [hunk 8]
```diff
@@ -0,0 +1,110 @@
...
+      throw MultipleArtifactsFoundException(
+        buildDir: buildDir,
+        foundArtifacts: candidates,
+      );
+    } else {
```
Comment (eseidel) [inline packages/shorebird_cli/lib/src/shorebird_android_artifacts.dart]: No need for else after return.

File: packages/shorebird_cli/lib/src/shorebird_android_artifacts.dart [hunk 9]
```diff
@@ -0,0 +1,110 @@
...
+      return candidates.first.path;
+    }
+  }
+
+  /// Find the app bundle in the build directory.
+  String? findAppBundle({
+    required String projectPath,
```
Comment (eseidel) [inline packages/shorebird_cli/lib/src/shorebird_android_artifacts.dart]: Should this be a File?  (I don't know what the CLI style is.  I recall @bryanoltman mentioning he tried to use File instead of String for most paths?)

File: packages/shorebird_cli/lib/src/commands/release/release_android_command.dart (hunk 1 above)
Comment (felangel) [reply packages/shorebird_cli/lib/src/commands/release/release_android_command.dart]: We can still have the top-level variables be non-nullable and only set the in the try block when we have successfully determined a bundlePath and apkPath.

File: packages/shorebird_cli/lib/src/shorebird_android_artifacts.dart (hunk 2 above)
Comment (felangel) [inline packages/shorebird_cli/lib/src/shorebird_android_artifacts.dart]:
```suggestion
/// Thrown when multiple artifacts are found in the build directory.
```

File: packages/shorebird_cli/lib/src/shorebird_android_artifacts.dart (hunk 4 above)
Comment (felangel) [reply packages/shorebird_cli/lib/src/shorebird_android_artifacts.dart:71]: For scoped instances, yes. This allows us to use a single instance of `ShorebirdAndroidArtifacts` throughout while also being able to override it in tests for mocking.

File: packages/shorebird_cli/lib/src/shorebird_android_artifacts.dart (hunk 6 above)
Comment (felangel) [reply packages/shorebird_cli/lib/src/shorebird_android_artifacts.dart:78]: Can we change the signature of this method to return a non-nullable `File` and throw an ArtifactNotFound exception in the case where an artifact isn't found?

File: packages/shorebird_cli/lib/src/shorebird_android_artifacts.dart (hunk 9 above)
Comment (felangel) [reply packages/shorebird_cli/lib/src/shorebird_android_artifacts.dart]: Same thing here regarding changing the signature to return a non-nullable `File` and throwing if an artifact is not found.

File: packages/shorebird_cli/lib/src/shorebird_android_artifacts.dart (hunk 2 above)
Comment (erickzanardo) [reply packages/shorebird_cli/lib/src/shorebird_android_artifacts.dart]: I should never happen as far I can tell, this was more of a "just to be sure" checking that Bryan suggested while we were discussing the solution.

File: packages/shorebird_cli/lib/src/shorebird_android_artifacts.dart (hunk 3 above)
Comment (erickzanardo) [reply packages/shorebird_cli/lib/src/shorebird_android_artifacts.dart:66]: Exactly!

File: packages/shorebird_cli/lib/src/shorebird_android_artifacts.dart [hunk 10]
```diff
@@ -0,0 +1,110 @@
...
+final shorebirdAndroidArtifactsRef = create(ShorebirdAndroidArtifacts.new);
+
+ShorebirdAndroidArtifacts get shorebirdAndroidArtifacts =>
+    read(shorebirdAndroidArtifactsRef);
+
+/// Mixin on [ShorebirdCommand] which exposes methods
+// to find the artifacts generated for android
+class ShorebirdAndroidArtifacts {
+  /// Find the artifact in the build directory.
+  String? findArtifact({
```
Comment (felangel) [inline packages/shorebird_cli/lib/src/shorebird_android_artifacts.dart]: Should this be private so that it forces callers to use the `findAppBundle` and `findAppApk` APIs?

File: packages/shorebird_cli/lib/src/shorebird_android_artifacts.dart (hunk 3 above)
Comment (felangel) [reply packages/shorebird_cli/lib/src/shorebird_android_artifacts.dart:66]: It would be nice to add a comment here explaining what this is doing and why we're using this method to compute an artifact id.

File: packages/shorebird_cli/lib/src/shorebird_android_artifacts.dart [hunk 11]
```diff
@@ -0,0 +1,110 @@
...
+    final artifactName =
+        flavor == null ? 'app-release.aab' : 'app-$flavor-release.aab';
+
+    return findArtifact(
+      buildDir: buildDir,
+      artifactName: artifactName,
+    );
+  }
+
+  /// Find the apk in the build directory.
```
Comment (felangel) [inline packages/shorebird_cli/lib/src/shorebird_android_artifacts.dart]:
```suggestion
  /// Find the apk in the provided [projectPath].
```

File: packages/shorebird_cli/lib/src/shorebird_android_artifacts.dart (hunk 2 above)
Comment (felangel) [reply packages/shorebird_cli/lib/src/shorebird_android_artifacts.dart]: Yeah I'm also concerned about this case. Have we filed an issue upstream for this bug?

File: packages/shorebird_cli/lib/src/commands/release/release_android_command.dart (hunk 1 above)
Comment (felangel) [reply packages/shorebird_cli/lib/src/commands/release/release_android_command.dart]: Better yet, see my comments about adjusting the signatures to return non-nullable types.

File: packages/shorebird_cli/test/src/shorebird_android_artifacts_test.dart [hunk 12]
```diff
@@ -0,0 +1,282 @@
...
+      expect(
+        shorebirdAndroidArtifacts.findApk(
+          projectPath: projectPath.path,
+          flavor: null,
+        ),
+        isNull,
+      );
+    });
+
+    test('find the app bundle without any flavors', () {
```
Comment (felangel) [inline packages/shorebird_cli/test/src/shorebird_android_artifacts_test.dart]:
```suggestion
    test('finds the app bundle without any flavors', () {
```

File: packages/shorebird_cli/test/src/shorebird_android_artifacts_test.dart [hunk 13]
```diff
@@ -0,0 +1,282 @@
...
+    test('returns null when cannot find the aab', () {
+      expect(
+        shorebirdAndroidArtifacts.findAppBundle(
+          projectPath: projectPath.path,
+          flavor: null,
+        ),
+        isNull,
+      );
+    });
+    test('returns null when cannot find the apk', () {
```
Comment (felangel) [inline packages/shorebird_cli/test/src/shorebird_android_artifacts_test.dart]:
```suggestion
    });

    test('returns null when an apk does not exist', () {
```

File: packages/shorebird_cli/test/src/shorebird_android_artifacts_test.dart [hunk 14]
```diff
@@ -0,0 +1,282 @@
...
+  group(ShorebirdAndroidArtifacts, () {
+    late Directory projectPath;
+    late ShorebirdAndroidArtifacts shorebirdAndroidArtifacts;
+
+    setUp(() {
+      projectPath = Directory.systemTemp.createTempSync();
+      shorebirdAndroidArtifacts = ShorebirdAndroidArtifacts();
+    });
+
+    test('returns null when cannot find the aab', () {
```
Comment (felangel) [inline packages/shorebird_cli/test/src/shorebird_android_artifacts_test.dart]:
```suggestion
    test('returns null when an aab does not exist', () {
```

File: packages/shorebird_cli/test/src/shorebird_android_artifacts_test.dart [hunk 15]
```diff
@@ -0,0 +1,282 @@
...
+
+      expect(
+        shorebirdAndroidArtifacts.findAppBundle(
+          projectPath: projectPath.path,
+          flavor: null,
+        ),
+        equals(artifact.path),
+      );
+    });
+    test('find the apk bundle without any flavors', () {
```
Comment (felangel) [inline packages/shorebird_cli/test/src/shorebird_android_artifacts_test.dart]:
```suggestion
    });

    test('finds the apk without any flavors', () {
```

Also might be nice to group these tests like:

```dart
group('when apk exists', () {
  group('when apk contains flavors', () {
    
  });

  group('when apk does not contain flavors', () {

  });
});

group('when apk does not exist', () {

});
```

File: packages/shorebird_cli/lib/src/shorebird_android_artifacts.dart (hunk 3 above)
Comment (erickzanardo) [reply packages/shorebird_cli/lib/src/shorebird_android_artifacts.dart:66]: Added, lmk if it is comprehensible

File: packages/shorebird_cli/test/src/shorebird_android_artifacts_test.dart [hunk 16]
```diff
@@ -13,22 +13,22 @@ void main() {
...
+        () => shorebirdAndroidArtifacts.findAppBundle(
           projectPath: projectPath.path,
           flavor: null,
         ),
-        isNull,
+        throwsA(isA<ArtifactNotFoundException>()),
       );
     });
-    test('returns null when cannot find the apk', () {
+    test('throws ArtifactNotFoundException when cannot find the apk', () {
```
Comment (bryanoltman) [inline packages/shorebird_cli/test/src/shorebird_android_artifacts_test.dart]:
```suggestion

    test('throws ArtifactNotFoundException when cannot find the apk', () {
```

File: packages/shorebird_cli/lib/src/shorebird_android_artifacts.dart (hunk 3 above)
Comment (bryanoltman) [reply packages/shorebird_cli/lib/src/shorebird_android_artifacts.dart:66]: Did you push the commit that adds the comment? I'm not seeing it on my end. Something like "Removes all non-word characters (i.e., `[^a-zA-Z0-9_]`) from the string" would be great.

Comment (bryanoltman) [reply packages/shorebird_cli/lib/src/shorebird_android_artifacts.dart:66]: Also mentioning the "why" is great too – I feel like we've had more cases of "why did we do that again?" this week than usual.

File: packages/shorebird_cli/lib/src/shorebird_android_artifacts.dart [hunk 17]
```diff
@@ -0,0 +1,110 @@
...
+    // Remove all non characters and digits from the artifact name.
+    final artifactId = artifactName.artifactId;
+
+    final directory = Directory(buildDir);
+    if (!directory.existsSync()) {
+      return null;
+    }
+
+    final allFiles = directory.listSync();
+    final candidates = allFiles.where((file) {
```
Comment (bryanoltman) [inline packages/shorebird_cli/lib/src/shorebird_android_artifacts.dart]: Maybe `aabArtifactCandidates`?

File: packages/shorebird_cli/lib/src/shorebird_android_artifacts.dart (hunk 9 above)
Comment (bryanoltman) [reply packages/shorebird_cli/lib/src/shorebird_android_artifacts.dart]: Yep, if this represents a Directory, it's better to use the semantically richer type.

File: packages/shorebird_cli/test/src/commands/release/release_android_command_test.dart [hunk 18]
```diff
@@ -274,6 +304,19 @@ void main() {
...
+      //    projectPath: any(named: 'projectPath'),
+      //    flavor: any(named: 'flavor'),
+      //  ),
+      //).thenReturn('app-release.aab');
+      //when(
+      //  () => shorebirdAndroidArtifacts.findApk(
+      //    projectPath: any(named: 'projectPath'),
+      //    flavor: any(named: 'flavor'),
+      //  ),
+      //).thenReturn('app-release.apk');
```
Comment (erickzanardo) [inline packages/shorebird_cli/test/src/commands/release/release_android_command_test.dart]:
```suggestion
```

File: packages/shorebird_cli/lib/src/shorebird_android_artifacts.dart (hunk 3 above)
Comment (erickzanardo) [reply packages/shorebird_cli/lib/src/shorebird_android_artifacts.dart:66]: @bryanoltman I pushed yes! I can see the comment in my PR, can you check again please?

File: packages/shorebird_cli/lib/src/shorebird_android_artifacts.dart [hunk 19]
```diff
@@ -0,0 +1,157 @@
...
+  final String buildDir;
+
+  @override
+  String toString() {
+    return 'Artifact $artifactName not found in $buildDir';
+  }
+}
+
+/// When building android artifacts, gradlew name these artifacts in a non
+/// consistent way.
```
Comment (bryanoltman) [inline packages/shorebird_cli/lib/src/shorebird_android_artifacts.dart]:
```suggestion
/// When building android artifacts, gradlew name these artifacts in an
/// inconsistent way.
```

File: packages/shorebird_cli/lib/src/shorebird_android_artifacts.dart [hunk 20]
```diff
@@ -0,0 +1,157 @@
...
+///  ...bundle/fullFlavorCamelCase/app-flavor1-flavor2-release.aab
+///
+/// The pattern follows for APKs.
+///
+/// The only thing that is consistent is the artifactId which is the name of the
+/// artifact will follow always the same order of name of the flavors.
+///
+/// So we create the idea of an identifier, which consistis in the file name
+/// without any special character and in lower case, that allows use to easily
+/// search in the build folder what was the artifact that was generated by the
```
Comment (bryanoltman) [inline packages/shorebird_cli/lib/src/shorebird_android_artifacts.dart]:
```suggestion
/// To get around this, we create an identifier for the artifact
/// that is the file name lowercased and without any non-word characters.
/// This allows use to reliably find the artifact generated by the
```

File: packages/shorebird_cli/lib/src/shorebird_android_artifacts.dart (hunk 3 above)
Comment (bryanoltman) [reply packages/shorebird_cli/lib/src/shorebird_android_artifacts.dart:66]: Yep, see it now. Added some suggestions 👍

File: packages/shorebird_cli/lib/src/shorebird_android_artifacts.dart (hunk 2 above)
Comment (erickzanardo) [reply packages/shorebird_cli/lib/src/shorebird_android_artifacts.dart]: Not yet. Was focusing on our PR first, will open now that it seems that I addressed all/most of the comments

File: packages/shorebird_cli/lib/src/commands/release/release_android_command.dart [hunk 21]
```diff
@@ -195,43 +195,33 @@ Use `shorebird flutter versions list` to list available versions.
...
-        final apkPath = flavor != null
-            ? p.join(
-                apkDirPath,
-                flavor,
-                'release',
-                'app-$flavor-release.apk',
-              )
-            : p.join(apkDirPath, 'release', 'app-release.apk');
+        final File bundleFile;
+        final File apkFile;
```
Comment (felangel) [inline packages/shorebird_cli/lib/src/commands/release/release_android_command.dart]:
```suggestion
        final File apkFile, bundleFile;
```

nit 🤷

File: packages/shorebird_cli/lib/src/shorebird_android_artifacts.dart [hunk 22]
```diff
@@ -0,0 +1,157 @@
...
+  final String artifactName;
+  final String buildDir;
+
+  @override
+  String toString() {
+    return 'Artifact $artifactName not found in $buildDir';
+  }
+}
+
+/// When building android artifacts, gradlew name these artifacts in an
```
Comment (felangel) [inline packages/shorebird_cli/lib/src/shorebird_android_artifacts.dart]:
```suggestion
/// When building android artifacts, gradlew names these artifacts in an
```

File: packages/shorebird_cli/lib/src/shorebird_android_artifacts.dart (hunk 17 above)
Comment (erickzanardo) [reply packages/shorebird_cli/lib/src/shorebird_android_artifacts.dart]: This method handles both aabs and apks, so `aabArtifactCandidates` would be wrong.

Gonna change to `artifactCandidates`

File: packages/shorebird_cli/lib/src/shorebird_android_artifacts.dart [hunk 23]
```diff
@@ -0,0 +1,157 @@
...
+///
+///  With multi dimensional flavors
+///  ...bundle/fullFlavorCamelCase/app-flavor1-flavor2-release.aab
+///
+/// The pattern follows for APKs.
+///
+/// The only thing that is consistent is the artifactId which is the name of the
+/// artifact will follow always the same order of name of the flavors.
+///
+/// To get around this, we create an identifier for the artifact
```
Comment (felangel) [inline packages/shorebird_cli/lib/src/shorebird_android_artifacts.dart:60]: Is there an upstream bug in Flutter tracking this? If so, can we link to it and add a TODO to revisit this workaround when the upstream bug is fixed?

Comment (erickzanardo) [reply packages/shorebird_cli/lib/src/shorebird_android_artifacts.dart:60]: I don't think that the upstream bug will make us no need this routine.

The bug that I gound in flutter tool is that if you try `flutter run --flavor developmentPlayStore`, whereas `PlayStore` is a flavor of its own, the tool will break the execution since it will not find the the apk.

If we look on the sourcecode of the flutter tool, we notice that they also do a routine it just don't include a logic to get that case, while the logic that we wrote on shorebirtd does.

File: packages/shorebird_cli/lib/src/shorebird_android_artifacts.dart (hunk 2 above)
Comment (erickzanardo) [reply packages/shorebird_cli/lib/src/shorebird_android_artifacts.dart]: Filled: https://github.com/flutter/flutter/issues/147261

File: packages/shorebird_cli/lib/src/commands/release/release_android_command.dart [hunk 24]
```diff
@@ -195,43 +195,32 @@ Use `shorebird flutter versions list` to list available versions.
...
-            : p.join(bundleDirPath, 'release', 'app-release.aab');
-        final apkPath = flavor != null
-            ? p.join(
-                apkDirPath,
-                flavor,
-                'release',
-                'app-$flavor-release.apk',
-              )
-            : p.join(apkDirPath, 'release', 'app-release.apk');
+        final File apkFile, bundleFile;
```
Comment (bryanoltman) [inline packages/shorebird_cli/lib/src/commands/release/release_android_command.dart]: I think we generally define one variable per line, even if they're of the same type.

File: packages/shorebird_cli/lib/src/shorebird_android_artifacts.dart [hunk 25]
```diff
@@ -0,0 +1,157 @@
...
+/// that is the file name lowercased and without any non-word characters.
+/// This allows use to reliably find the artifact generated by the
```
Comment (bryanoltman) [inline packages/shorebird_cli/lib/src/shorebird_android_artifacts.dart]:
```suggestion
/// This allows us to reliably find the artifact generated by the
```

File: packages/shorebird_cli/lib/src/shorebird_android_artifacts.dart [hunk 26]
```diff
@@ -0,0 +1,157 @@
...
+      'flutter-apk',
+    );
+
+    final artifaceName =
+        flavor == null ? 'app-release.apk' : 'app-$flavor-release.apk';
+
+    return _findArtifact(
+      directory: Directory(buildDir),
+      artifactName: artifaceName,
+    );
```
Comment (bryanoltman) [inline packages/shorebird_cli/lib/src/shorebird_android_artifacts.dart]:
```suggestion
    final artifactName =
        flavor == null ? 'app-release.apk' : 'app-$flavor-release.apk';

    return _findArtifact(
      directory: Directory(buildDir),
      artifactName: artifactName,
    );
```

File: packages/shorebird_cli/lib/src/shorebird_android_artifacts.dart [hunk 27]
```diff
@@ -0,0 +1,157 @@
...
+    required Directory directory,
+  }) {
+    // Remove all non characters and digits from the artifact name.
+    final artifactId = artifactName.artifactId;
+
+    if (!directory.existsSync()) {
+      throw ArtifactNotFoundException(
+        artifactName: artifactName,
+        buildDir: directory.path,
+      );
```
Comment (bryanoltman) [inline packages/shorebird_cli/lib/src/shorebird_android_artifacts.dart:88]: Should we throw the same type of exception in both the "we got a bad directory" case and the "we didn't find any artifacts in a good directory" case? It could be that we don't care, but just checking in case we do.

File: packages/shorebird_cli/test/src/commands/release/release_android_command_test.dart [hunk 28]
```diff
@@ -888,5 +920,71 @@ Note: ${lightCyan.wrap('shorebird patch android --flavor=$flavor --target=$targe
       expect(exitCode, equals(ExitCode.success.code));
       verifyNever(() => logger.confirm(any()));
     });
+
+    test('error when the app bundle cannot be found ', () async {
```
Comment (bryanoltman) [inline packages/shorebird_cli/test/src/commands/release/release_android_command_test.dart]:
```suggestion
    test('error when the app bundle cannot be found', () async {
```

File: packages/shorebird_cli/test/src/commands/release/release_android_command_test.dart [hunk 29]
```diff
@@ -888,5 +920,71 @@ Note: ${lightCyan.wrap('shorebird patch android --flavor=$flavor --target=$targe
...
+        ),
+      );
+      final exitCode = await runWithOverrides(command.run);
+      verify(
+        () => logger.err('Artifact app-release.aab not found in buildDir'),
+      ).called(1);
+      expect(exitCode, ExitCode.software.code);
+    });
+
+    test('error when the apk cannot be found ', () async {
```
Comment (bryanoltman) [inline packages/shorebird_cli/test/src/commands/release/release_android_command_test.dart]:
```suggestion
    test('error when the apk cannot be found', () async {
```

File: packages/shorebird_cli/test/src/commands/release/release_android_command_test.dart [hunk 30]
```diff
@@ -888,5 +920,71 @@ Note: ${lightCyan.wrap('shorebird patch android --flavor=$flavor --target=$targe
...
+      shorebirdAndroidArtifacts = MockShorebirdAndroidArtifacts();
+      when(
+        () => shorebirdAndroidArtifacts.findAppBundle(
+          project: any(named: 'project'),
+          flavor: any(named: 'flavor'),
+        ),
+      ).thenReturn(File('app-release.aab'));
```
Comment (bryanoltman) [inline packages/shorebird_cli/test/src/commands/release/release_android_command_test.dart]: Is this override here because we try to find an aab before looking for an apk?

File: packages/shorebird_cli/test/src/commands/release/release_android_command_test.dart [hunk 31]
```diff
@@ -888,5 +920,71 @@ Note: ${lightCyan.wrap('shorebird patch android --flavor=$flavor --target=$targe
...
+        ),
+      );
+      final exitCode = await runWithOverrides(command.run);
+      verify(
+        () => logger.err('Artifact app-release.apk not found in buildDir'),
+      ).called(1);
+      expect(exitCode, ExitCode.software.code);
+    });
+
+    test('error when multiple artifacts are found ', () async {
```
Comment (bryanoltman) [inline packages/shorebird_cli/test/src/commands/release/release_android_command_test.dart]:
```suggestion
    test('error when multiple artifacts are found', () async {
```

File: packages/shorebird_cli/test/src/mocks.dart [hunk 32]
```diff
@@ -149,3 +150,6 @@ class MockStdin extends Mock implements Stdin {}
 class MockValidator extends Mock implements Validator {}
 
 class MockXcodeBuild extends Mock implements XcodeBuild {}
+
+class MockShorebirdAndroidArtifacts extends Mock
+    implements ShorebirdAndroidArtifacts {}
```
Comment (bryanoltman) [inline packages/shorebird_cli/test/src/mocks.dart]: The Mocks in this file are alphabetical, this should be higher up

File: packages/shorebird_cli/test/src/shorebird_android_artifacts_test.dart [hunk 33]
```diff
@@ -0,0 +1,347 @@
...
+          expect(
+            () => shorebirdAndroidArtifacts.findApk(
+              project: project,
+              flavor: null,
+            ),
+            throwsA(isA<ArtifactNotFoundException>()),
+          );
+        });
+      });
+      group('when build folder exists but not the file', () {
```
Comment (bryanoltman) [inline packages/shorebird_cli/test/src/shorebird_android_artifacts_test.dart]:
```suggestion
      });

      group('when build folder exists but not the file', () {
```

File: packages/shorebird_cli/test/src/shorebird_android_artifacts_test.dart [hunk 34]
```diff
@@ -0,0 +1,347 @@
...
+          ).createSync(recursive: true);
+          expect(
+            () => shorebirdAndroidArtifacts.findAppBundle(
+              project: project,
+              flavor: null,
+            ),
+            throwsA(isA<ArtifactNotFoundException>()),
+          );
+        });
+        test('throws ArtifactNotFoundException for apks', () {
```
Comment (bryanoltman) [inline packages/shorebird_cli/test/src/shorebird_android_artifacts_test.dart]:
```suggestion
        });

        test('throws ArtifactNotFoundException for apks', () {
```

File: packages/shorebird_cli/test/src/shorebird_android_artifacts_test.dart [hunk 35]
```diff
@@ -0,0 +1,347 @@
...
+          shorebirdAndroidArtifacts
+              .findAppBundle(
+                project: project,
+                flavor: null,
+              )
+              .path,
+          equals(artifact.path),
+        );
+      });
+      test('finds the apk', () {
```
Comment (bryanoltman) [inline packages/shorebird_cli/test/src/shorebird_android_artifacts_test.dart]:
```suggestion
      });

      test('finds the apk', () {
```

File: packages/shorebird_cli/test/src/shorebird_android_artifacts_test.dart [hunk 36]
```diff
@@ -0,0 +1,347 @@
...
+              .findAppBundle(
+                project: project,
+                flavor: flavor,
+              )
+              .path,
+          equals(artifact.path),
+        );
+      });
+      test('finds the apk', () {
+        final artifactPath = path.join(
```
Comment (bryanoltman) [inline packages/shorebird_cli/test/src/shorebird_android_artifacts_test.dart]:
```suggestion
      });

      test('finds the apk', () {
        final artifactPath = path.join(
```

File: packages/shorebird_cli/test/src/shorebird_android_artifacts_test.dart [hunk 37]
```diff
@@ -0,0 +1,347 @@
...
+          shorebirdAndroidArtifacts
+              .findAppBundle(
+                project: project,
+                flavor: flavor,
+              )
+              .path,
+          equals(artifact.path),
+        );
+      });
+      test('finds the apk with multi dimensional flavors', () {
```
Comment (bryanoltman) [inline packages/shorebird_cli/test/src/shorebird_android_artifacts_test.dart]:
```suggestion
      });

      test('finds the apk with multi dimensional flavors', () {
```

File: packages/shorebird_cli/test/src/shorebird_android_artifacts_test.dart [hunk 38]
```diff
@@ -0,0 +1,347 @@
...
+          shorebirdAndroidArtifacts
+              .findAppBundle(
+                project: project,
+                flavor: flavor,
+              )
+              .path,
+          equals(artifact.path),
+        );
+      });
+      test('finds the apk', () {
```
Comment (bryanoltman) [inline packages/shorebird_cli/test/src/shorebird_android_artifacts_test.dart]:
```suggestion
      });

      test('finds the apk', () {
```

File: packages/shorebird_cli/test/src/shorebird_android_artifacts_test.dart [hunk 39]
```diff
@@ -0,0 +1,347 @@
...
+
+        expect(
+          () => shorebirdAndroidArtifacts.findAppBundle(
+            project: project,
+            flavor: flavor,
+          ),
+          throwsA(isA<MultipleArtifactsFoundException>()),
+        );
+      });
+      test('throws when finding multiple apk files', () {
```
Comment (bryanoltman) [inline packages/shorebird_cli/test/src/shorebird_android_artifacts_test.dart]:
```suggestion
      });

      test('throws when finding multiple apk files', () {
```

File: packages/shorebird_cli/test/src/shorebird_android_artifacts_test.dart [hunk 40]
```diff
@@ -0,0 +1,347 @@
...
+          'build',
+          'app',
+          'outputs',
+          'bundle',
+          'internalRelease',
+          'app-internal-release.aab',
+        );
+        final artifact = File(
+          path.join(project.path, artifactPath),
+        )..createSync(recursive: true);
```
Comment (bryanoltman) [inline packages/shorebird_cli/test/src/shorebird_android_artifacts_test.dart:140]: This could be in the group's setUp

File: packages/shorebird_cli/test/src/shorebird_android_artifacts_test.dart [hunk 41]
```diff
@@ -0,0 +1,347 @@
...
+        test('throws ArtifactNotFoundException for aabs', () {
+          expect(
+            () => shorebirdAndroidArtifacts.findAppBundle(
+              project: project,
+              flavor: null,
+            ),
+            throwsA(isA<ArtifactNotFoundException>()),
+          );
+        });
+        test('throws ArtifactNotFoundException for apks', () {
```
Comment (bryanoltman) [inline packages/shorebird_cli/test/src/shorebird_android_artifacts_test.dart]:
```suggestion
        });

        test('throws ArtifactNotFoundException for apks', () {
```

File: packages/shorebird_cli/test/src/shorebird_android_artifacts_test.dart [hunk 42]
```diff
@@ -0,0 +1,347 @@
...
+          Directory(
+            path.join(
+              project.path,
+              'build',
+              'app',
+              'outputs',
+              'bundle',
+              'release',
+            ),
+          ).createSync(recursive: true);
```
Comment (bryanoltman) [inline packages/shorebird_cli/test/src/shorebird_android_artifacts_test.dart]: This could be in the group's setUp (instead of in the test itself)

File: packages/shorebird_cli/test/src/shorebird_android_artifacts_test.dart [hunk 43]
```diff
@@ -0,0 +1,347 @@
...
+          'build',
+          'app',
+          'outputs',
+          'bundle',
+          'release',
+          'app-release.aab',
+        );
+        final artifact = File(
+          path.join(project.path, artifactPath),
+        )..createSync(recursive: true);
```
Comment (bryanoltman) [inline packages/shorebird_cli/test/src/shorebird_android_artifacts_test.dart:91]: Same here re: being in a setUp function instead of in the test

**Review by bryanoltman — APPROVED** [review]
A bunch of small stylistic comments, but overall LGTM

File: packages/shorebird_cli/lib/src/commands/release/release_android_command.dart (hunk 24 above)
Comment (felangel) [reply packages/shorebird_cli/lib/src/commands/release/release_android_command.dart]: My fault, I suggested a one liner. I'm happy either way we should probably enforce one or the other via lint rules.

Comment (erickzanardo) [reply packages/shorebird_cli/lib/src/commands/release/release_android_command.dart]: Agree with the lint rule 😅

File: packages/shorebird_cli/lib/src/shorebird_android_artifacts.dart (hunk 26 above)
Comment (erickzanardo) [reply packages/shorebird_cli/lib/src/shorebird_android_artifacts.dart]: oh, big typo, good catch

File: packages/shorebird_cli/test/src/commands/release/release_android_command_test.dart (hunk 30 above)
Comment (erickzanardo) [reply packages/shorebird_cli/test/src/commands/release/release_android_command_test.dart]: Exactly, so the `findAppBundle` cannot fail, otherwise the test will not fail because of the reason that we want it to fail

File: packages/shorebird_cli/lib/src/commands/release/release_android_command.dart (hunk 24 above)
Comment (erickzanardo) [reply packages/shorebird_cli/lib/src/commands/release/release_android_command.dart]: Screenshot 2024-04-23 at 19 11 44

the lint actually complain, I wonder why the CI didn't catch this?

File: packages/shorebird_cli/lib/src/shorebird_android_artifacts.dart (hunk 27 above)
Comment (erickzanardo) [reply packages/shorebird_cli/lib/src/shorebird_android_artifacts.dart:88]: I feel it is not worth differentiating since the action is the same.

Unless we can think in any different action for each case?

File: packages/shorebird_cli/test/src/shorebird_android_artifacts_test.dart (hunk 42 above)
Comment (erickzanardo) [reply packages/shorebird_cli/test/src/shorebird_android_artifacts_test.dart]: I am unsure, each of the tests uses a different path since one is about aabs and the other about apks, which lives in different places. So I fail to see the benefit.

Or maybe I am missing something?

File: packages/shorebird_cli/bin/shorebird.dart [hunk 44]
```diff
@@ -61,6 +62,7 @@ Future<void> main(List<String> args) async {
         shorebirdValidatorRef,
         shorebirdVersionRef,
         xcodeBuildRef,
+        shorebirdAndroidArtifactsRef,
```
Comment (felangel) [inline packages/shorebird_cli/bin/shorebird.dart]: Can we keep this list sorted alphabetically?

File: packages/shorebird_cli/lib/src/commands/release/release_android_command.dart [hunk 45]
```diff
@@ -195,43 +195,33 @@ Use `shorebird flutter versions list` to list available versions.
...
-                'app-$flavor-release.apk',
-              )
-            : p.join(apkDirPath, 'release', 'app-release.apk');
+        final File apkFile;
+        final File bundleFile;
+        try {
+          bundleFile = shorebirdAndroidArtifacts.findAppBundle(
+            project: projectRoot,
+            flavor: flavor,
+          );
```
Comment (felangel) [inline packages/shorebird_cli/lib/src/commands/release/release_android_command.dart]:
```suggestion
        final File apkFile;
        final File aabFile;
        try {
          aabFile = shorebirdAndroidArtifacts.findAab(
            project: projectRoot,
            flavor: flavor,
          );
```

Minor but for consistency might want to rename?

File: packages/shorebird_cli/bin/shorebird.dart (hunk 44 above)
Comment (erickzanardo) [reply packages/shorebird_cli/bin/shorebird.dart]: I wish there were a linter that could check those things :*(

File: packages/shorebird_cli/lib/src/commands/release/release_android_command.dart [hunk 46]
```diff
@@ -195,43 +195,33 @@ Use `shorebird flutter versions list` to list available versions.
...
+        final File aabFile;
+        try {
+          aabFile = shorebirdAndroidArtifacts.findAppBundle(
+            project: projectRoot,
+            flavor: flavor,
+          );
+          apkFile = shorebirdAndroidArtifacts.findApk(
+            project: projectRoot,
+            flavor: flavor,
+          );
```
Comment (bryanoltman) [inline packages/shorebird_cli/lib/src/commands/release/release_android_command.dart]: Missed this the first time, but this reads like it will always fail unless `generateApk` is true.

File: packages/shorebird_cli/test/src/commands/release/release_android_command_test.dart (hunk 30 above)
Comment (bryanoltman) [reply packages/shorebird_cli/test/src/commands/release/release_android_command_test.dart]: 👍  I'd maybe leave a small comment so that's clear

File: packages/shorebird_cli/test/src/shorebird_android_artifacts_test.dart (hunk 42 above)
Comment (bryanoltman) [reply packages/shorebird_cli/test/src/shorebird_android_artifacts_test.dart]: In this case, it's probably not necessary.

File: packages/shorebird_cli/lib/src/commands/release/release_android_command.dart [hunk 47]
```diff
@@ -195,43 +195,35 @@ Use `shorebird flutter versions list` to list available versions.
...
-                apkDirPath,
-                flavor,
-                'release',
-                'app-$flavor-release.apk',
-              )
-            : p.join(apkDirPath, 'release', 'app-release.apk');
+        late final File apkFile;
+        final File aabFile;
+        try {
+          aabFile = shorebirdAndroidArtifacts.findAppBundle(
```
Comment (felangel) [inline packages/shorebird_cli/lib/src/commands/release/release_android_command.dart]:
```suggestion
          aabFile = shorebirdAndroidArtifacts.findAab(
```

minor but might want to rename for consistency

File: packages/shorebird_cli/lib/src/shorebird_android_artifacts.dart [hunk 48]
```diff
@@ -0,0 +1,157 @@
+import 'package:path/path.dart' as p;
+import 'package:scoped/scoped.dart';
+import 'package:shorebird_cli/src/command.dart';
+import 'package:shorebird_cli/src/third_party/flutter_tools/lib/flutter_tools.dart';
```
Comment (felangel) [inline packages/shorebird_cli/lib/src/shorebird_android_artifacts.dart]: What is this import used for?

File: packages/shorebird_cli/test/src/commands/release/release_android_command_test.dart [hunk 49]
```diff
@@ -888,5 +920,72 @@ Note: ${lightCyan.wrap('shorebird patch android --flavor=$flavor --target=$targe
       expect(exitCode, equals(ExitCode.success.code));
       verifyNever(() => logger.confirm(any()));
     });
+
+    test('error when the app bundle cannot be found', () async {
```
Comment (felangel) [inline packages/shorebird_cli/test/src/commands/release/release_android_command_test.dart]:
```suggestion
    test('errors when the app bundle cannot be found', () async {
```

File: packages/shorebird_cli/test/src/commands/release/release_android_command_test.dart [hunk 50]
```diff
@@ -888,5 +920,72 @@ Note: ${lightCyan.wrap('shorebird patch android --flavor=$flavor --target=$targe
...
+        ),
+      );
+      final exitCode = await runWithOverrides(command.run);
+      verify(
+        () => logger.err('Artifact app-release.aab not found in buildDir'),
+      ).called(1);
+      expect(exitCode, ExitCode.software.code);
+    });
+
+    test('error when the apk cannot be found', () async {
```
Comment (felangel) [inline packages/shorebird_cli/test/src/commands/release/release_android_command_test.dart]:
```suggestion
    test('errors when the apk cannot be found', () async {
```

File: packages/shorebird_cli/test/src/commands/release/release_android_command_test.dart [hunk 51]
```diff
@@ -888,5 +920,72 @@ Note: ${lightCyan.wrap('shorebird patch android --flavor=$flavor --target=$targe
...
+        ),
+      );
+      final exitCode = await runWithOverrides(command.run);
+      verify(
+        () => logger.err('Artifact app-release.apk not found in buildDir'),
+      ).called(1);
+      expect(exitCode, ExitCode.software.code);
+    });
+
+    test('error when multiple artifacts are found', () async {
```
Comment (felangel) [inline packages/shorebird_cli/test/src/commands/release/release_android_command_test.dart]:
```suggestion
    test('errors when multiple artifacts are found', () async {
```

File: packages/shorebird_cli/test/src/shorebird_android_artifacts_test.dart [hunk 52]
```diff
@@ -0,0 +1,355 @@
...
+  group(ShorebirdAndroidArtifacts, () {
+    late Directory project;
+    late ShorebirdAndroidArtifacts shorebirdAndroidArtifacts;
+
+    setUp(() {
+      project = Directory.systemTemp.createTempSync();
+      shorebirdAndroidArtifacts = ShorebirdAndroidArtifacts();
+    });
+
+    group('when cannot find artifacts', () {
```
Comment (felangel) [inline packages/shorebird_cli/test/src/shorebird_android_artifacts_test.dart]: Is this group necessary?

File: packages/shorebird_cli/test/src/shorebird_android_artifacts_test.dart [hunk 53]
```diff
@@ -0,0 +1,355 @@
...
+                project: project,
+                flavor: flavor,
+              )
+              .path,
+          equals(artifact.path),
+        );
+      });
+    });
+
+    group('when with multi dimensional flavors', () {
```
Comment (felangel) [inline packages/shorebird_cli/test/src/shorebird_android_artifacts_test.dart]:
```suggestion
    group('when using multi-dimensional flavors', () {
```

File: packages/shorebird_cli/test/src/shorebird_android_artifacts_test.dart [hunk 54]
```diff
@@ -0,0 +1,355 @@
...
+                project: project,
+                flavor: null,
+              )
+              .path,
+          equals(artifact.path),
+        );
+      });
+    });
+
+    group('with one dimensional flavor', () {
```
Comment (felangel) [inline packages/shorebird_cli/test/src/shorebird_android_artifacts_test.dart]:
```suggestion
    group('when using single-dimensional flavor', () {
```

File: packages/shorebird_cli/test/src/shorebird_android_artifacts_test.dart [hunk 55]
```diff
@@ -0,0 +1,355 @@
...
+              project: project,
+              flavor: null,
+            ),
+            throwsA(isA<ArtifactNotFoundException>()),
+          );
+        });
+      });
+    });
+
+    group('with no flavors', () {
```
Comment (felangel) [inline packages/shorebird_cli/test/src/shorebird_android_artifacts_test.dart]:
```suggestion
    group('when using no flavors', () {
```

File: packages/shorebird_cli/test/src/shorebird_android_artifacts_test.dart [hunk 56]
```diff
@@ -0,0 +1,355 @@
...
+                flavor: flavor,
+              )
+              .path,
+          equals(artifact.path),
+        );
+      });
+    });
+
+    group('when with multi dimensional flavors', () {
+      test('finds the app bundle with multi dimensional flavors', () {
```
Comment (felangel) [inline packages/shorebird_cli/test/src/shorebird_android_artifacts_test.dart]:
```suggestion
      test('finds the app bundle', () {
```

File: packages/shorebird_cli/test/src/shorebird_android_artifacts_test.dart [hunk 57]
```diff
@@ -0,0 +1,355 @@
...
+              .findAppBundle(
+                project: project,
+                flavor: flavor,
+              )
+              .path,
+          equals(artifact.path),
+        );
+      });
+
+      test('finds the apk with multi dimensional flavors', () {
```
Comment (felangel) [inline packages/shorebird_cli/test/src/shorebird_android_artifacts_test.dart]:
```suggestion
      test('finds the apk', () {
```

File: packages/shorebird_cli/test/src/shorebird_android_artifacts_test.dart [hunk 58]
```diff
@@ -0,0 +1,355 @@
...
+                project: project,
+                flavor: flavor,
+              )
+              .path,
+          equals(artifact.path),
+        );
+      });
+    });
+
+    group('when with multi dimensional flavors and mult word flavor name', () {
```
Comment (felangel) [inline packages/shorebird_cli/test/src/shorebird_android_artifacts_test.dart]:
```suggestion
    group('when using multi-dimensional flavors and multi-word flavor name', () {
```

File: packages/shorebird_cli/test/src/shorebird_android_artifacts_test.dart [hunk 59]
```diff
@@ -0,0 +1,355 @@
...
+                flavor: flavor,
+              )
+              .path,
+          equals(artifact.path),
+        );
+      });
+    });
+
+    group('when finding multiple files', () {
+      test('throws when finding multiple aab files', () {
```
Comment (felangel) [inline packages/shorebird_cli/test/src/shorebird_android_artifacts_test.dart]:
```suggestion
      test('throws MultipleArtifactsFoundException when looking for aab', () {
```

File: packages/shorebird_cli/test/src/shorebird_android_artifacts_test.dart [hunk 60]
```diff
@@ -0,0 +1,355 @@
...
+                project: project,
+                flavor: flavor,
+              )
+              .path,
+          equals(artifact.path),
+        );
+      });
+    });
+
+    group('when finding multiple files', () {
```
Comment (felangel) [inline packages/shorebird_cli/test/src/shorebird_android_artifacts_test.dart]:
```suggestion
    group('when multiple files are found', () {
```

File: packages/shorebird_cli/test/src/shorebird_android_artifacts_test.dart [hunk 61]
```diff
@@ -0,0 +1,355 @@
...
+        expect(
+          () => shorebirdAndroidArtifacts.findAppBundle(
+            project: project,
+            flavor: flavor,
+          ),
+          throwsA(isA<MultipleArtifactsFoundException>()),
+        );
+      });
+
+      test('throws when finding multiple apk files', () {
```
Comment (felangel) [inline packages/shorebird_cli/test/src/shorebird_android_artifacts_test.dart]:
```suggestion
      test('throws MultipleArtifactsFoundException when looking for apk', () {
```

**Review by felangel — APPROVED** [review]
LGTM just left a bunch of small recommendations

File: packages/shorebird_cli/lib/src/shorebird_android_artifacts.dart (hunk 48 above)
Comment (erickzanardo) [reply packages/shorebird_cli/lib/src/shorebird_android_artifacts.dart]: apparently it exposes `dart:io` classes and I might auto selecting it, changed to `dart:io`
