### PR TITLE
fix(shorebird_cli): print error message if user attempts to preview iOS on linux or windows

### LINKED ISSUE #970: fix: `shorebird preview` for iOS silently fails on windows
```
PS C:\Users\micro\Documents\GitHub\test_counter> shorebird preview
✓ Fetching apps (0.2s)
Which app would you like to preview?
❯ ◉  fluttercon_demo
  ◯  hello_shorebird
  ◯  ios_test
  ◯  shorebird_code_push
  ◯  shorebird_code_push_example
  ◯  shorebird_hello
  ◯  test_app
  ◯  test_counter
Which app would you like to preview?
  ◯  fluttercon_demo
❯ ◉  hello_shorebird
  ◯  ios_test
  ◯  shorebird_code_push
  ◯  shorebird_code_push_example
  ◯  shorebird_hello
  ◯  test_app
  ◯  test_counter
Which app would you like to preview?
  ◯  fluttercon_demo
  ◯  hello_shorebird
❯ ◉  ios_test
  ◯  shorebird_code_push
  ◯  shorebird_code_push_example
  ◯  shorebird_hello
  ◯  test_app
  ◯  test_counter
Which app would you like to preview?
  ◯  fluttercon_demo
  ◯  hello_shorebird
  ◯  ios_test
❯ ◉  shorebird_code_push
  ◯  shorebird_code_push_example
  ◯  shorebird_hello
  ◯  test_app
  ◯  test_counter
Which app would you like to preview?
  ◯  fluttercon_demo
  ◯  hello_shorebird
  ◯  ios_test
  ◯  shorebird_code_push
❯ ◉  shorebird_code_push_example
  ◯  shorebird_hello
  ◯  test_app
  ◯  test_counter
Which app would you like to preview?
  ◯  fluttercon_demo
  ◯  hello_shorebird
  ◯  ios_test
  ◯  shorebird_code_push
  ◯  shorebird_code_push_example
❯ ◉  shorebird_hello
  ◯  test_app
  ◯  test_counter
Which app would you like to preview?
  ◯  fluttercon_demo
  ◯  hello_shorebird
  ◯  ios_test
  ◯  shorebird_code_push
  ◯  shorebird_code_push_example
  ◯  shorebird_hello
❯ ◉  test_app
  ◯  test_counter
Which app would you like to preview?
  ◯  fluttercon_demo
  ◯  hello_shorebird
  ◯  ios_test
  ◯  shorebird_code_push
  ◯  shorebird_code_push_example
❯ ◉  shorebird_hello
  ◯  test_app
  ◯  test_counter
Which app would you like to preview?
  ◯  fluttercon_demo
  ◯  hello_shorebird
  ◯  ios_test
  ◯  shorebird_code_push
❯ ◉  shorebird_code_push_example
  ◯  shorebird_hello
  ◯  test_app
  ◯  test_counter
Which app would you like to preview?
  ◯  fluttercon_demo
  ◯  hello_shorebird
  ◯  ios_test
❯ ◉  shorebird_code_push
  ◯  shorebird_code_push_example
  ◯  shorebird_hello
  ◯  test_app
  ◯  test_counter
Which app would you like to preview?
  ◯  fluttercon_demo
  ◯  hello_shorebird
❯ ◉  ios_test
  ◯  shorebird_code_push
  ◯  shorebird_code_push_example
  ◯  shorebird_hello
  ◯  test_app
  ◯  test_counter
Which app would you like to preview? ios_test
✓ Fetching releases (0.1s)
Which release would you like to preview?
❯ ◉  1.0.0+16
  ◯  1.0.0+15
  ◯  1.0.0+14
  ◯  1.0.0+13
  ◯  1.0.0+12
  ◯  1.0.0+11
  ◯  1.0.0+10
  ◯  1.0.0+9
  ◯  1.0.0+8
  ◯  1.0.0+7
  ◯  1.0.0+6
  ◯  1.0.0+5
  ◯  1.0.0+4
  ◯  1.0.0+3
  ◯  1.0.0+2
  ◯  1.0.0+1
Which release would you like to preview? 1.0.0+16
Which platform would you like to preview?
❯ ◉  ios
Which platform would you like to preview? ios
✓ Fetching runner artifact (90ms)
✓ Downloading release (4.0s)
```

### PR DESCRIPTION
**Pull request by bryanoltman**
## Description

Print helpful error instead of failing silently if user tries to preview an unsupported platform (this currently only means "previewing iOS on linux or windows")

Fixes https://github.com/shorebirdtech/shorebird/issues/970

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

File: packages/shorebird_cli/lib/src/commands/preview_command.dart [hunk 1]
```diff
@@ -45,10 +46,9 @@ class PreviewCommand extends ShorebirdCommand {
       )
       ..addOption(
         'platform',
-        allowed: [ReleasePlatform.android.name, ReleasePlatform.ios.name],
+        allowed: ReleasePlatform.values.map((e) => e.name),
```
Comment (felangel) [inline packages/shorebird_cli/lib/src/commands/preview_command.dart:49]: 💯

**Review by felangel — APPROVED** [review]
