### PR TITLE
fix(shorebird_cli): ensure release artifacts are all built using the same flutter revision

### LINKED ISSUE #1894: fix: patch created with wrong snapshot version
App ID: `0a08c1df-3a32-4d30-b8ce-40d62ef55c8f`

**Description**

faced a strange issue where the patch was causing the app to crash on opening, we had done patch updates in the past but have not faced this issue. Unfortunately have to deactivate the patch.

We do not have actual logs It happened to some ground users and the patch rollout was too slow. Fortunately received mail from the play console where I can find the logs 

`[FATAL:flutter/runtime/dart_vm_initializer.cc(89)] Error while initializing the Dart VM: Wrong full snapshot version, expected '<<SOME ID>>' found '<<Another ID >>`

Even these crashes are not logged on to the Firebase crashlytics 

Same scenario I tried today on the development environment creating the same release and providing the same patch and now it works and this time rollout was also quick.

Here is the result of `shorebird doctor` 

```
Shorebird 0.18.2 • git@github.com:shorebirdtech/shorebird.git
Flutter 3.13.9 • revision 39df2792f537b1fc62a9c668a6990f585bd91456
Engine • revision e81fa131e59506d9f6af2a0cee7de749131f1bf0

✗ Shorebird is up-to-date (0.6s)
  [!] A new version of shorebird is available! Run `shorebird upgrade` to upgrade.
✓ Flutter install is correct (0.2s)
✓ AndroidManifest.xml files contain INTERNET permission (36ms)
✓ Has access to storage.googleapis.com (44ms)
```

### PR DESCRIPTION
**Pull request by felangel**
## Description

- fix(shorebird_cli): ensure release artifacts are all built using the same flutter revision
  - closes #1894
  
  
Screenshot 2024-04-16 at 1 51 07 PM

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [X] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

File: packages/shorebird_cli/lib/src/commands/release/release_command.dart [hunk 1]
```diff
@@ -22,6 +22,27 @@ class ReleaseCommand extends ShorebirdCommand {
...
+    required String releaseVersion,
+  }) {
+    logger.err(
+      '''
+${styleBold.wrap(lightRed.wrap('A release with version $releaseVersion already exists but was built using a different Flutter revision.'))}
+
+  Existing release built with: ${lightCyan.wrap(existingFlutterRevision)}
+  Current release built with: ${lightCyan.wrap(currentFlutterRevision)}
+
+${styleBold.wrap(lightRed.wrap('All releases for the given version must be built using the same Flutter version.'))}
```
Comment (eseidel) [inline packages/shorebird_cli/lib/src/commands/release/release_command.dart]: I think you mean "All platforms for a given release must use the same Flutter version."?

**Review by eseidel — APPROVED** [review]
