### PR TITLE
fix(shorebird_cli): download from storage bucket to verify access to storage.googleapis.com

### LINKED ISSUE #1506: Update "does shorebird work from my country" faq
The point is to explain to customers how to teach reachability of shorebird's servers.

Maybe instead we should include this as part of `shorebird doctor`?

Confusion: https://discord.com/channels/1030243211995791380/1174569116875628574/1174571036059115520

### PR DESCRIPTION
**Pull request by bryanoltman**
## Description

Users who were blocked from accessing our storage buckets could successfully ping storage.googleapis.com, making this check misleading. We now attempt to download a file, which should (hopefully) yield a more accurate diagnostic.

Fixes https://github.com/shorebirdtech/shorebird/issues/1506

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

File: packages/shorebird_cli/lib/src/validators/storage_access_validator.dart [hunk 1]
```diff
@@ -9,15 +8,11 @@ class StorageAccessValidator extends Validator {
...
-      [
-        // Execute a single ping.
-        if (platform.isWindows) ...['/n', '1'] else ...['-c', '1'],
-        'storage.googleapis.com',
-      ],
+    final testFileUrl = Uri.parse(
+      'https://storage.googleapis.com/shorebird_doctor/hello',
     );
-    if (result.exitCode != ExitCode.success.code) {
+    final result = await httpClient.get(testFileUrl);
```
Comment (felangel) [inline packages/shorebird_cli/lib/src/validators/storage_access_validator.dart:14]: Should we also check the contents of the file?

**Review by felangel — APPROVED** [review]

File: packages/shorebird_cli/lib/src/validators/storage_access_validator.dart (hunk 1 above)
Comment (bryanoltman) [reply packages/shorebird_cli/lib/src/validators/storage_access_validator.dart:14]: Done
